//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIM {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OpenFOAMExportResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OpenFOAMExportResource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BIM.OpenFOAMExportResource", typeof(OpenFOAMExportResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STLFile was not saved.x ähnelt.
        /// </summary>
        internal static string CANCEL_FILE_NOT_SAVED {
            get {
                return ResourceManager.GetString("CANCEL_FILE_NOT_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occur an unknown error,the application will be terminated. ähnelt.
        /// </summary>
        internal static string ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File is ReadOnly. ähnelt.
        /// </summary>
        internal static string ERR_FILE_READONLY {
            get {
                return ResourceManager.GetString("ERR_FILE_READONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Format for string: ähnelt.
        /// </summary>
        internal static string ERR_FORMAT {
            get {
                return ResourceManager.GetString("ERR_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Occur an IO error,the application will be terminated. ähnelt.
        /// </summary>
        internal static string ERR_IO_EXCEPTION {
            get {
                return ResourceManager.GetString("ERR_IO_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There is no solid in this document. ähnelt.
        /// </summary>
        internal static string ERR_NOSOLID {
            get {
                return ResourceManager.GetString("ERR_NOSOLID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save STLFile has failed. ähnelt.
        /// </summary>
        internal static string ERR_SAVE_FILE_FAILED {
            get {
                return ResourceManager.GetString("ERR_SAVE_FILE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Make sure you have the required permission to read or write files. ähnelt.
        /// </summary>
        internal static string ERR_SECURITY_EXCEPTION {
            get {
                return ResourceManager.GetString("ERR_SECURITY_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The vector entries cannot be converted into double. ähnelt.
        /// </summary>
        internal static string ERR_VECTOR_FORMAT {
            get {
                return ResourceManager.GetString("ERR_VECTOR_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STL Exporter ähnelt.
        /// </summary>
        internal static string MESSAGE_BOX_TITLE {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die .stl ähnelt.
        /// </summary>
        internal static string SAVE_DIALOG_DEFAULT_FILE_EXTEND {
            get {
                return ResourceManager.GetString("SAVE_DIALOG_DEFAULT_FILE_EXTEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stl files (*.stl)|*.stl|All files (*.*)|*.* ähnelt.
        /// </summary>
        internal static string SAVE_DIALOG_FILE_FILTER {
            get {
                return ResourceManager.GetString("SAVE_DIALOG_FILE_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: All linked models must use the same Project Location Position as the host model ähnelt.
        /// </summary>
        internal static string WARN_PROJECT_POSITION {
            get {
                return ResourceManager.GetString("WARN_PROJECT_POSITION", resourceCulture);
            }
        }
    }
}
