tap 'homebrew/core'
tap 'homebrew/science'
tap 'hlrs-vis/tap'

brew 'cmake'

brew 'xerces-c'
brew 'boost'
brew 'assimp'
brew 'jpeg-turbo'
brew 'libtiff'
brew 'giflib'
brew 'libpng'
brew 'qt5'
brew 'glew'
brew 'ffmpeg'
brew 'vtk'
#brew 'cgns'
brew 'hdf5'
brew 'netcdf'
brew 'swig'
brew 'python3'
brew 'freetype'

brew 'snappy'
brew 'teem'
brew 'gdcm'
brew 'hlrs-vis/tap/volpack'

brew 'mpich'
brew 'open-scene-graph'
brew 'audiofile'
brew 'freealut'
brew 'proj'
brew 'gdal'
brew 'eigen'
brew 'hlrs-vis/tap/osgcal'
brew 'hlrs-vis/tap/opencrg'

#brew 'tbb'
#brew 'homebrew/science/hdf5', args: ['with-mpi']
#brew 'hlrs-vis/tap/covise'
#brew 'hlrs-vis/tap/libvncserver'
