#ifndef VRML_C4D_SYMBOLS_H
#define VRML_C4D_SYMBOLS_H
enum
{
	// string table definitions
	IDS_GRADIENTTITLE	= 10000,
	IDS_TYPE,
	IDS_INTERPOLATION,
	IDS_NONE,
	IDS_LINEAR,
	IDS_EXPUP,
	IDS_EXPDOWN,
	IDS_SMOOTH,
	IDS_POSITION,
	IDS_SPHERIZE,
	IDS_ROUNDED_TUBE,
	IDS_TRIANGULATE,
	IDS_VIDEOPOST,
	IDS_ATOM,
	IDS_ATOM_POINT,
	IDS_ATOM_EDGE,
	IDS_CIRCLE,
	IDS_LISTVIEW,

	IDS_LOOKATCAMERA,
	IDS_SIMPLEMATERIAL,
	IDS_PARTICLEVOLUME,
	IDS_MANDELBROT,
	IDS_SDKGRADIENT,
	IDS_BITMAPDISTORTION,
	IDS_BLINKER,
	IDS_GRAVITATION,

	IDS_BFF,
	IDS_STL,
	IDS_MENUTEST,
	IDS_ASYNCTEST,
	IDS_ACTIVEOBJECT,

	IDC_SERIALNUMBER,
	DLG_REGISTER,

  IDS_PARTICLEVOLUME_HIGH_DENSITY,
  IDS_PARTICLEVOLUME_LOW_DENSITY,

	// IDs for the global string table
	IDS_APPLY_FILTER,
	IDS_THRESHOLD,
	IDS_MATRIX,

	// threshold dialog
	DLG_THRESHOLD,
	GADGET_THRESHOLD_SLIDER_LEVELS,
	GADGET_THRESHOLD_DOCUMENT_PREVIEW,
	GADGET_THRESHOLD_PREVIEWGROUP,

	// sample matrix dialog
	DLG_SMPL_MATRIX,
	GADGET_SMPL_MATRIX_SLIDER_MIX,
	GADGET_SMPL_MATRIX_SLIDER_ANGLE,
	GADGET_SMPL_MATRIX_DOCUMENT_PREVIEW,
	GADGET_SMPL_MATRIX_TEXTURE_MODE,
	GADGET_SMPL_MATRIX_TYPE_POPUP,
	GADGET_SMPL_MATRIX_PREVIEWGROUP,

	DLG_LISTVIEW,
	GADGET_INSERT,
	GADGET_REMOVE,
	GADGET_LISTVIEW1,
	GADGET_LISTVIEW2,
	IDS_PRIMITIVETOOL,

	IDS_SUBDIALOG,
	DLG_SUBDIALOG,
	GADGET_SUBDIALOG,
	GADGET_SUB1,
	GADGET_SUB2,

	DLG_VIDEOPOST,
	IDS_VPINVERTIMAGE,
	IDS_MORPHMIXER,
	IDS_IMPORTFAILED,
	IDS_MORPHSELECT,

	IDS_VPVISUALIZEPOST,
	IDS_VPRECONSTRUCT,

	IDS_HLP_EDGECUT_SDK,
	IDS_EDGECUT_SDK,
	IDS_HLP_REVERSE_NORMALS_SDK,
	IDS_REVERSE_NORMALS_SDK,

	IDS_LAYER_SHADER_BROWSER,

  // Dialog definitions of IDD_SHADER_BROWSER start here
  IDD_SHADER_BROWSER,
  IDC_LAYER_BROWSER_LINK,
  IDC_LAYER_BROWSER_TREE,
  IDC_LAYER_BROWSER_PROPS,
  // Dialog definitions of IDD_SHADER_BROWSER end here

	// Falloff types
	IDS_RANDOMFALLOFF,

	// Effectors
	IDS_NOISEEFFECTOR,
	IDS_DROPEFFECTOR,

	// Hair
	IDS_HAIR_DEFOMER_EXAMPLE,
	IDS_HAIR_FORCE_EXAMPLE,
	IDS_HAIR_COLLIDER_EXAMPLE,
	IDS_HAIR_CONSTRAINT_EXAMPLE,
	IDS_HAIR_GRASS_EXAMPLE,
	IDS_HAIR_SHADER_EXAMPLE,
	IDS_HAIR_VIDEOPOST_EXAMPLE,
	IDS_HAIR_STYLING_EXAMPLE,
	IDS_HAIR_RENDERING_EXAMPLE,
	IDS_HAIR_GENERATOR_EXAMPLE,

  // Dialog definitions of IDD_VRMLEXP_DLG start here
  IDD_VRMLEXP_DLG,
  IDS_HEADLINE,
  IDC_STATICTEXT1,
  IDC_CHECK_COPYTEXTURES,
  IDC_COMBO_TEXTUREEXPORT,
  IDC_REPLACEALL,
  IDC_SKIPEXISTING,
  IDC_ASKREPLACE,
  IDC_CHECK_SETTEXTUREDOBJECTCOLORWHITE,
  IDC_AMBIENTINTENSITY,
  IDC_EDIT_IDC_CHECK_AMBIENTINTENSITY,
  IDC_CHECK_EXPORTNORMALS,
  IDC_STATIC_TEXT_DATAFORMAT,
  IDC_COMBO_DATAFORMAT,
  IDC_OPENCOVERVRMLMOD,
  IDC_NORMALVRML,
  IDC_STATIC_TEXT_DONTEXPORTWHEN,
  IDC_CHECK_VISIBILITYEDITOR,
  IDC_CHECK_VISIBILITYRENDER,
  IDC_STATIC_TEXT_ANIMATION,
  IDC_CHECK_WRITEANIMATION,
  IDC_STATIC_NOOFKEYFRAMES,
  IDC_EDIT1_NOOFKEYFRAMES,
  // Dialog definitions of IDD_VRMLEXP_DLG end here

//ID zur Wiedererkennung der speziell Erstellten Objekte: 
	I_M_A_NAVIGATIONINFO_OBJECT, 
	I_M_A_LOD_OBJECT,
	I_M_A_REGULAR_OBJECT,

// End of symbol definition
  _DUMMY_ELEMENT_
};
 
#endif