#!/bin/sh
#
# remotedaemon	 This scripts starts the remote daemon
#
# chkconfig: 345 99 01
# description: 	Remote COVISE daemon

. /etc/rc.d/init.d/functions

prog=RemoteDaemon

export COVISEDIR=/mnt/raid/svn/wcs/trunk/covise/

case "$1" in 
start)
    echo -n "Starting ${prog}: "
    daemon ${COVISEDIR}/bin/RemoteDaemon -d
    touch /var/lock/subsys/remoted
    echo
    exit 0
    ;;
stop)
    echo -n "Shutting down ${prog}: "
    killproc RemoteDaemon
    rm -f /var/lock/subsys/remoted
    echo
    ;;
restart)
    $0 stop
    $0 start
    ;;
*)
    echo $"Usage: $0 {start|stop|restart}"
    RETVAL=1
esac
    
exit $RETVAL


