IF(PTHREADS_INCLUDE_DIR)
  SET(PTHREADS_FIND_QUIETLY TRUE)
ENDIF(PTHREADS_INCLUDE_DIR)


FIND_PATH(PTHREADS_INCLUDE_DIR pthread.h
   PATHS
   $ENV{PTHREADS_HOME}/include
   $ENV{EXTERNLIBS}/pthread/include
   $ENV{EXTERNLIBS}/pthreads/include
   /usr/include
   DOC "The directory where pthread.h resides"
)
MARK_AS_ADVANCED(PTHREADS_INCLUDE_DIR)

IF (MSVC)
    
      FIND_LIBRARY(PTHREADS_LIBRARY_DEBUG NAMES pthreadVC2d.lib
        PATHS
        $ENV{PTHREADS_HOME}/lib
        $ENV{EXTERNLIBS}/pthreads/lib
      )
      FIND_LIBRARY(PTHREADS_LIBRARY_RELEASE NAMES pthreadVC2.lib
        PATHS
        $ENV{PTHREADS_HOME}/lib
        $ENV{EXTERNLIBS}/pthreads/lib
      )
      IF (PTHREADS_LIBRARY_DEBUG AND PTHREADS_LIBRARY_RELEASE)
         SET(PTHREADS_LIBRARIES optimized ${PTHREADS_LIBRARY_RELEASE} debug ${PTHREADS_LIBRARY_DEBUG})
      ELSE (PTHREADS_LIBRARY_DEBUG AND PTHREADS_LIBRARY_RELEASE)
         SET(PTHREADS_LIBRARIES NOTFOUND)
         MESSAGE(STATUS "Could not find the debug AND release version of pthreads lib")
      ENDIF (PTHREADS_LIBRARY_DEBUG AND PTHREADS_LIBRARY_RELEASE)
    MARK_AS_ADVANCED(PTHREADS_LIBRARY_DEBUG PTHREADS_LIBRARY_RELEASE)
    

ELSE (MSVC)
  
  SET(PTHREADS_NAMES ${PTHREADS_NAMES} pthread)
  FIND_LIBRARY(PTHREADS_LIBRARY NAMES ${PTHREADS_NAMES}
    PATHS
    $ENV{PTHREADS_HOME}/lib
    $ENV{EXTERNLIBS}/pthread/lib
    $ENV{EXTERNLIBS}/pthreads/lib
    /usr/lib
    /usr/lib32
    /usr/lib64
    /usr/local/lib
    /opt/local/lib
    DOC "The pthread library"
  )
  FIND_LIBRARY(PTHREADS_LIBRARY NAMES ${PTHREADS_NAMES})

  IF (PTHREADS_LIBRARY)
    SET(PTHREADS_LIBRARIES ${PTHREADS_LIBRARY})
  ELSE (PTHREADS_LIBRARY)
    SET(PTHREADS_LIBRARIES NOTFOUND)
    MESSAGE(STATUS "Could not find pthread-library")    
  ENDIF (PTHREADS_LIBRARY)
  MARK_AS_ADVANCED(PTHREADS_LIBRARY)
  
ENDIF (MSVC)

INCLUDE(FindPackageHandleStandardArgs)

IF(MSVC)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(PTHREADS DEFAULT_MSG PTHREADS_LIBRARY_RELEASE PTHREADS_LIBRARY_DEBUG PTHREADS_INCLUDE_DIR)
  MARK_AS_ADVANCED(PTHREADS_LIBRARY_RELEASE PTHREADS_LIBRARY_DEBUG)
ELSE(MSVC)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(PTHREADS DEFAULT_MSG PTHREADS_LIBRARY PTHREADS_INCLUDE_DIR)
  MARK_AS_ADVANCED(PTHREADS_LIBRARY)
ENDIF(MSVC)
