@ECHO OFF
ECHO COVISE variables are...
ECHO ARCHSUFFIX=%ARCHSUFFIX%
ECHO COVISEDIR=%COVISEDIR%
ECHO EXTERNLIBS=%EXTERNLIBS%
ECHO COVISE_PATH=%COVISE_PATH%
ECHO COFRAMEWORKDIR=%COFRAMEWORKDIR%
ECHO COVISECONFIG_DEBUG=%COVISECONFIG_DEBUG%
ECHO DIRSCRIPTS=%DIRSCRIPTS%
ECHO SVN_SSH=%SVN_SSH%
ECHO PYTHONHOME=%PYTHONHOME%
ECHO QTDIR=%QTDIR%
