#ifndef COVER_HTTPCLIENT_CURL_EXPORT_H
#define COVER_HTTPCLIENT_CURL_EXPORT_H

#include <util/coExport.h>

#if defined(coCurlHTTPClient_EXPORTS)
#define CURLHTTPCLIENTEXPORT COEXPORT
#else
#define CURLHTTPCLIENTEXPORT COIMPORT
#endif

#endif // COVER_HTTPCLIENT_CURL_EXPORT_H