C    ++++++++++++++++++++++++++++++++++++
C    +                                  +
C    +    Covise SimLib include file    +
C    +                                  +
C    ++++++++++++++++++++++++++++++++++++

C --- Commands
      INTEGER CONOCO,COVINI,COFINI,COEXEC

C --- Data Object Creation
      INTEGER COSU1D,COSU3D

C --- Parameter Requests
      INTEGER COGPFL,COGPSL,COGPIN,COGPCH,COGPBO,COGPTX

C --- binary reading/writing
      INTEGER CORECV,COSEND

C --- request verbose level
      INTEGER COVERB

C --- attach an attribute
      INTEGER COATTR

C --- parallel stuff
      INTEGER COPAIN,COPAPO,COPACM,COPAVM,COPANO
