#ifndef _pqFLEPanel_h
#define _pqFLEPanel_h

#include "pqAutoGeneratedObjectPanel.h"
#include "pqObjectPanelInterface.h"

class pqFLEPanel : public pqAutoGeneratedObjectPanel
{
    Q_OBJECT
public:
    pqFLEPanel(pqProxy *proxy, QWidget *p);
    ~pqFLEPanel();

private slots:
    void onUnsteadyChanged(int state);
    void onModeChanged(int index);
};

#endif
