//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by vrmlexp.rc
//
#define IDS_DB_TRIGGER_DIST             1
#define IDS_ANIM_PICK_MODE              2
#define IDREPLACEALL                    2
#define IDS_LOD_PICK_MODE               3
#define IDSKIP                          3
#define IDS_OPEN_FAILED                 4
#define IDSKIPALL                       4
#define IDS_HL_TITLE                    5
#define IDS_VPT_TITLE                   6
#define IDS_ANIM_TITLE                  7
#define IDS_ACTION_TITLE                8
#define IDS_TRIGGERS_TITLE              9
#define IDS_LOD_TITLE                   10
#define IDS_VRML_INS_TITLE              11
#define IDS_LIBDESCRIPTION              12
#define IDS_VRML_EXPORT                 13
#define IDS_DS_AMBIENT                  14
#define IDS_DS_DIFFUSE                  15
#define IDS_DS_SPECULAR                 16
#define IDS_DS_NONE                     17
#define IDS_DS_LOCKAD                   18
#define IDS_DS_LOCKCOL                  19
#define IDS_DS_PARAMCHG                 20
#define IDS_DS_LOCK_DS                  21
#define IDS_DS_BASIC                    22
#define IDS_DS_SHININESS                23
#define IDS_DS_SELFI                    24
#define IDS_DS_OPACITY                  25
#define IDS_DS_MAP_TEXTURE_ERR          26
#define IDS_DS_INVAL_NAME               27
#define IDS_DS_SELECT_FILE              28
#define IDS_DS_STANDARD                 29
#define IDS_DS_BITMAP                   30
#define IDS_TH_SCENEEXPORT              31
#define IDS_TimeSensor_PICK_MODE        32
#define IDS_TouchSensor_PICK_MODE       33
#define IDS_POLYGON_COUNTER_CLASS       34
#define IDS_ANCHOR_CLASS                35
#define IDS_TOUCH_SENSOR_CLASS          36
#define IDS_TIME_SENSOR_CLASS           37
#define IDS_NAV_INFO_CLASS              38
#define IDS_BACKGROUND_CLASS            39
#define IDS_FOG_CLASS                   40
#define IDS_AUDIO_CLIP_CLASS            41
#define IDS_SOUND_CLASS                 42
#define IDS_BILLBOARD_CLASS             43
#define IDS_LOD_CLASS                   44
#define IDS_INLINE_CLASS                45
#define IDS_ANCHOR                      46
#define IDS_TOUCH_SENSOR                47
#define IDS_TIME_SENSOR                 48
#define IDS_NAV_INFO                    49
#define IDS_BACKGROUND                  50
#define IDS_FOG                         51
#define IDS_AUDIO_CLIP                  52
#define IDS_SOUND                       53
#define IDS_BILLBOARD                   54
#define IDS_LOD                         55
#define IDS_INLINE                      56
#define IDS_VRML_EXPORT_CLASS           57
#define IDS_PROX_SENSOR_CLASS           58
#define IDS_PROX_SENSOR                 59
#define IDS_AR_SENSOR                   60
#define IDS_AR_SENSOR_CLASS             61
#define IDS_ARSensor_PICK_MODE          62
#define IDS_COVER_PICK_MODE             63
#define IDS_COVER_SENSOR                64
#define IDS_COVER_SENSOR_CLASS          65
#define IDS_SWITCH                      66
#define IDS_SWITCH_CLASS                67
#define IDS_Switch_PICK_MODE            68
#define IDS_PICK_TRIGGER                69
#define IDS_PICK_AUDIOCLIP              70
#define IDS_OUT_TRIANGLES               71
#define IDS_OUT_QUADS                   72
#define IDS_OUT_NGONS                   73
#define IDS_OUT_VIS_EDGES               74
#define IDS_VISIBLE_EDGES               75
#define IDS_NGONS                       76
#define IDS_QUADS                       77
#define IDS_ONOFF_SWITCH                78
#define IDS_ONOFF_SWITCH_CLASS          79
#define IDS_OnOffSwitch_PICK_MODE       80
#define IDS_RB_ResetPivot_CLASS         81
#define IDS_RB_ResetPivot               82
#define IDS_TABLETUI                    83
#define IDS_TABLETUI_CLASS              84
#define IDS_TabletUI_PICK_MODE          85
#define IDS_BB_PARAMS                   86
#define IDS_BB_SIZE                     87
#define IDS_BB_SCREEN_ALIGN             88
#define IDS_VRML_SCRIPT_TITLE           89
#define IDS_SCRIPT_CLASS                90
#define IDS_SCRIPT                      91
#define IDS_CAL3D_CLASS                 92
#define IDS_CAL3D                       93
#define IDS_CAL3D_TITLE                 94
#define IDS_VRML_COVISEOOBJECT_TITLE    95
#define IDS_COVISEOBJECT_CLASS          96
#define IDS_COVISEOBJECT_CLASS2         97
#define IDS_COVISEOBJECT                97
#define IDD_PANEL                       101
#define IDD_CPPOUT_PANEL                103
#define IDD_LOD                         116
#define IDD_SCRIPT                      117
#define IDD_VRBLEXP                     118
#define IDD_URL_BOOKMARKS               119
#define IDC_LOD_CURSOR                  122
#define IDB_VMTL_BUTTONS                122
#define IDC_ANIM_CURSOR                 123
#define IDB_VMTL_MASKBUTTONS            123
#define IDD_SAMPLE_RATES                127
#define IDD_WORLD_INFO                  129
#define IDD_ABOUT                       130
#define IDD_PROGRESSDLG                 131
#define IDS_SKY                         132
#define IDS_SKY_CLASS                   133
#define IDC_CROSS_HAIR                  156
#define IDD_POLYCOUNT                   329
#define IDC_CLOSEBUTTON                 1000
#define IDC_CHECKDEP                    1001
#define IDC_CPPOUT_PICK                 1002
#define IDC_USE_MATLIB                  1032
#define IDD_TimeSensor                  1034
#define IDD_NAV_INFO                    1035
#define IDD_BACKGROUND_COLORS           1036
#define IDD_BACKGROUND_IMAGES           1037
#define IDD_FOG                         1038
#define IDD_AUDIO_CLIP                  1039
#define IDC_COLOR_SWATCH_2              1040
#define IDD_SOUND                       1040
#define IDC_COLOR_SWATCH_3              1041
#define IDD_TOUCH_SENSOR                1041
#define IDD_PROX_SENSOR                 1042
#define IDD_BACKGROUND_COLORS1          1043
#define IDD_ANCHOR                      1044
#define IDD_BBOARD                      1045
#define IDD_AR_SENSOR                   1046
#define IDD_COVER                       1047
#define IDD_SWITCH                      1048
#define IDD_ONOFF_SWITCH                1049
#define IDD_ResetPivot_PANEL            1050
#define IDD_TABLETUI                    1051
#define IDD_CONFIRM                     1052
#define IDD_SKY                         1053
#define IDD_INS                         1054
#define IDD_TUISLIDER                   1055
#define IDD_MT_SENSOR                   1056
#define IDD_TUIBUTTON                   1057
#define IDD_TUIFRAME                    1058
#define IDD_TUISPLITTER                 1059
#define IDD_TUICOMBOBOX                 1060
#define IDC_TFORM_ONCE                  1061
#define IDC_HYPERLINK                   1061
#define IDD_CAL3D                       1061
#define IDC_COORD_ONCE                  1062
#define IDD_INS1                        1062
#define IDD_COVISEOOBJECT               1062
#define IDC_FLIPBOOK_ONCE               1063
#define IDC_URL                         1068
#define IDC_URL_PREFIX                  1068
#define IDC_TITLE                       1068
#define IDC_BACK                        1068
#define IDC_INFO                        1069
#define IDC_BOTTOM                      1069
#define IDC_FRONT                       1070
#define IDC_LEFT                        1071
#define IDC_RIGHT                       1072
#define IDC_TOP                         1073
#define IDC_LOD_SIZE                    1094
#define IDC_LOD_SIZE_SPINNER            1095
#define IDC_LOD_PICK                    1096
#define IDC_LOD_DIST                    1098
#define IDC_LOD_DIST_SPINNER            1099
#define IDC_LOD_LIST                    1101
#define IDC_LOD_DEL                     1102
#define IDC_INS_URL                     1103
#define IDC_INS_SIZE                    1104
#define IDC_INS_SIZE_SPINNER            1105
#define IDC_INS_BBOX_SIZE               1106
#define IDC_INS_BBOX_DEF                1107
#define IDC_GENNORMALS                  1109
#define IDC_INDENT                      1110
#define IDC_CPV_CALC                    1111
#define IDC_CAMERA_COMBO                1113
#define IDC_ADD                         1114
#define IDC_NAV_INFO_COMBO              1114
#define IDC_DELETE                      1115
#define IDC_BACKGROUND_COMBO            1115
#define IDC_IMPORT                      1116
#define IDC_FOG_COMBO                   1116
#define IDC_FOG_COMBO2                  1117
#define IDC_SKY_COMBO                   1117
#define IDC_DESC                        1118
#define IDC_URL_LIST                    1120
#define IDC_BOOKMARKS                   1121
#define IDC_USE_PREFIX                  1127
#define IDC_DIGITS                      1136
#define IDC_FILE_FORMAT                 1137
#define IDC_POLY_COUNT                  1139
#define IDC_SEL_COUNT                   1140
#define IDC_POLY_BAR                    1141
#define IDC_SELECTED_BAR                1142
#define IDC_LOOP                        1144
#define IDC_START_EDIT                  1147
#define IDC_START_SPIN                  1148
#define IDC_STOP_EDIT                   1149
#define IDC_STOP_SPIN                   1150
#define IDC_COORD_INTERP                1151
#define IDC_MAX_FRONT_EDIT              1151
#define IDC_MAX_FRONT_SPIN              1152
#define IDC_FLIP_BOOK                   1152
#define IDC_SAMPLE_RATES                1153
#define IDC_DEF_USE                     1154
#define IDC_TFORM_CUSTOM                1156
#define IDC_USELOD                      1156
#define IDC_TFORM_EDIT                  1157
#define IDC_USELOD2                     1157
#define IDC_EXPORTLIGHTS                1157
#define IDC_TFORM_SPIN                  1158
#define IDC_COPYTEXTURES                1158
#define IDC_COORD_EDIT                  1159
#define IDC_TimeSensor_SIZE             1159
#define IDC_COLOR_3_ANGLE_EDIT          1159
#define IDC_Occluder                    1159
#define IDC_COORD_SPIN                  1160
#define IDC_TimeSensor_SIZE_SPINNER     1160
#define IDC_COLOR_3_ANGLE_SPIN          1160
#define IDC_FORCE_WHITE                 1160
#define IDC_COORD_CUSTOM                1161
#define IDC_TimeSensor_PICK             1161
#define IDC_EXPORTLIGHTS2               1161
#define IDC_EXPORT_WORLD_SPACE          1161
#define IDC_TimeSensor_LIST             1162
#define IDC_FLIPBOOK_EDIT               1162
#define IDC_TimeSensor_DEL              1163
#define IDC_FLIPBOOK_SPIN               1163
#define IDC_HEADLIGHT                   1164
#define IDC_FLIPBOOK_CUSTOM             1164
#define IDC_TimeSensor_CYCLE            1164
#define IDC_VIS_LIMIT_EDIT              1165
#define IDC_TimeSensor_CYCLE_SPIN       1165
#define IDC_VIS_LIMIT_SPIN              1166
#define IDC_COLLISION_EDIT              1167
#define IDC_COLLISION_SPIN              1168
#define IDC_TYPE                        1169
#define IDC_TERRAIN_EDIT                1170
#define IDC_TERRAIN_SPIN                1171
#define IDC_STEP_EDIT                   1172
#define IDC_STEP_SPIN                   1173
#define IDC_SPEED_EDIT                  1174
#define IDC_SPEED_SPIN                  1175
#define IDC_WORLD_INFO                  1176
#define IDC_SCALE_EDIT                  1176
#define IDC_EXP_HELP                    1177
#define IDC_SCALE_SPIN                  1177
#define IDC_EXPORT_HIDDEN               1178
#define IDC_PRIM                        1179
#define IDC_1_COLOR                     1180
#define IDC_ENABLE_PROGRESS_BAR         1180
#define IDC_2_COLOR                     1181
#define IDC_COLOR_PER_VERTEX            1181
#define IDC_COLOR_PER_VERTEX1           1181
#define IDC_SCALE_SPIN3                 1181
#define IDC_3_COLOR                     1182
#define IDC_COLOR_SWATCH_1              1183
#define IDC_COLOR_2_ANGLE_EDIT          1184
#define IDC_COLOR_2_ANGLE_SPIN          1185
#define IDC_COLOR_SWATCH                1187
#define IDC_VR_EDIT                     1188
#define IDC_VR_SPIN                     1189
#define IDC_LONGITUDE_EDIT              1190
#define IDC_PITCH_EDIT                  1191
#define IDC_LONGITUDE_SPIN              1191
#define IDC_PITCH_SPIN                  1192
#define IDC_HOUR_EDIT                   1192
#define IDC_INTENSITY_EDIT              1193
#define IDC_HOUR_SPIN                   1193
#define IDC_INTENSITY_SPIN              1194
#define IDC_YEAR_EDIT                   1194
#define IDC_MIN_BACK_EDIT               1195
#define IDC_YEAR_SPIN                   1195
#define IDC_MIN_BACK_SPIN               1196
#define IDC_MONTH_EDIT                  1196
#define IDC_MIN_FRONT_EDIT              1197
#define IDC_MONTH_SPIN                  1197
#define IDC_MIN_FRONT_SPIN              1198
#define IDC_DAY_EDIT                    1198
#define IDC_MAX_BACK_EDIT               1199
#define IDC_DAY_SPIN                    1199
#define IDC_MAX_BACK_SPIN               1200
#define IDC_LATITUDE_EDIT               1200
#define IDC_NAME                        1201
#define IDC_LATITUDE_SPIN               1201
#define IDC_AUDIO_CLIP_PICK             1202
#define IDC_ALTITUDE_EDIT               1202
#define IDC_SPATIALIZE                  1203
#define IDC_ALTITUDE_SPIN               1203
#define IDC_PRIORITY_EDIT               1204
#define IDC_START_ON_LOAD               1204
#define IDC_RADIUS_EDIT                 1204
#define IDC_PRIORITY_SPIN               1205
#define IDC_RADIUS_SPIN                 1205
#define IDC_ICON_EDIT                   1206
#define IDC_ICON_SPIN                   1207
#define IDC_ENABLE                      1209
#define IDC_PICK                        1210
#define IDC_SIZE_EDIT                   1211
#define IDC_PICK_EXIT                   1211
#define IDC_SIZE_SPIN                   1212
#define IDC_TUISLIDER_MAX_EDIT          1212
#define IDC_TUIMAX_EDIT                 1212
#define IDC_LIST                        1213
#define IDC_TUISLIDER_VALUE_EDIT        1213
#define IDC_TUIVALUE_EDIT               1213
#define IDC_DEL                         1214
#define IDC_TUISLIDER_TICKS_EDIT        1214
#define IDC_TUIVAL_EDIT                 1214
#define IDC_WIDTH_EDIT                  1215
#define IDC_PICK_PARENT                 1215
#define IDC_DEFAULT_EDIT                1215
#define IDC_DEL2                        1215
#define IDC_TUIOBJECT_LIST              1216
#define IDC_WIDTH_SPIN                  1216
#define IDC_HEADING_ONLY                1216
#define IDC_DEFAULT_SPIN                1216
#define IDC_PICK_OFF                    1216
#define IDC_ELEMENT_LIST                1216
#define IDC_TUIELEMENT_LIST             1216
#define IDC_HEIGHT_EDIT                 1217
#define IDC_FREEZE                      1217
#define IDC_DEFAULT_EDIT2               1217
#define IDC_POSY_EDIT                   1217
#define IDC_HEIGHT_SPIN                 1218
#define IDC_CURRENT_CAMERA              1218
#define IDC_DEFAULT_SPIN2               1218
#define IDC_POSY_SPIN                   1218
#define IDC_LENGTH_EDIT                 1219
#define IDC_DEFAULT_EDIT3               1219
#define IDC_POSX_EDIT                   1219
#define IDC_MOVEUP                      1219
#define IDC_LENGTH_SPIN                 1220
#define IDC_DEFAULT_SPIN3               1220
#define IDC_POSX_SPIN                   1220
#define IDC_MOVEDOWN                    1220
#define IDC_TRIGGER_OBJ                 1221
#define IDC_LIST_EXIT                   1221
#define IDC_RECONNECT                   1221
#define IDC_DEL_EXIT                    1222
#define IDC_OFF_OBJ                     1222
#define IDC_TUIELEMENT_DEL              1223
#define IDC_ORI_EDIT                    1225
#define IDC_ANCHOR_URL                  1226
#define IDC_ORI_SPIN                    1226
#define IDC_PARAMETER                   1227
#define IDC_CAMERA                      1228
#define IDC_POS_EDIT                    1228
#define IDC_SET_CAMERA                  1229
#define IDC_POS_SPIN                    1229
#define IDC_ALIGN                       1230
#define IDC_POLYGON_TYPE                1231
#define IDC_MY_EDIT                     1232
#define IDC_MY_SPIN                     1233
#define IDC_MX_EDIT                     1234
#define IDC_MX_SPIN                     1235
#define IDC_PROGRESS_NNAME              1236
#define IDC_MAY_EDIT                    1236
#define IDC_MAY_SPIN                    1237
#define IDC_CPV_MAX                     1238
#define IDC_MAX_EDIT                    1238
#define IDC_MZ_EDIT                     1239
#define IDC_MZ_SPIN                     1240
#define IDC_MAZ_EDIT                    1241
#define IDC_MAZ_SPIN                    1242
#define IDC_MAX_SPIN                    1243
#define IDC_IPZ_EDIT                    1244
#define IDC_IPZ_SPIN                    1245
#define IDC_IPY_EDIT                    1246
#define IDC_IPY_SPIN                    1247
#define IDC_IPX_EDIT                    1248
#define IDC_IPX_SPIN                    1249
#define IDC_MARKER_NAME                 1250
#define IDC_ALLOW_NONE                  1251
#define IDC_R_EDIT                      1251
#define IDC_ON_OBJ                      1252
#define IDC_R_SPIN                      1252
#define IDC_PICK_ON                     1253
#define IDC_P_EDIT                      1253
#define IDC_KEY_CODE                    1254
#define IDC_P_SPIN                      1254
#define IDC_RESETTM_SELECTED            1255
#define IDC_H_EDIT                      1255
#define IDC_COMBO1                      1256
#define IDC_H_SPIN                      1256
#define IDC_COMBO2                      1257
#define IDC_TUISHAPE_COMBO              1257
#define IDC_DEFAULT_STATE               1258
#define IDC_COMBO4                      1262
#define IDC_EDIT1                       1264
#define IDC_TUIELEMENTNAME_EDIT         1264
#define IDC_SURFACE_MODE                1264
#define IDC_PARENT_COMBOBOX             1265
#define IDC_EDIT2                       1266
#define IDC_SOURCE_NAME                 1268
#define IDC_DESTINATION_NAME            1269
#define IDC_ENABLED                     1270
#define IDC_CURRENTTIME                 1271
#define IDC_TIMELAPSE                   1272
#define IDC_MINUTE_SPIN                 1273
#define IDC_MINUTE_EDIT                 1274
#define IDC_SCRIPT_URL                  1283
#define IDC_SCRIPT_BBOX_SIZE            1284
#define IDC_SCRIPT_BBOX_DEF             1285
#define IDC_SCRIPT_SIZE                 1286
#define IDC_SCRIPT_SIZE_SPINNER         1287
#define IDC_TUIOBJECT_CREATE            1292
#define IDC_TUIELEMENT_CREATE           1292
#define IDC_TUISLIDER_Label1            1294
#define IDC_TUISLIDER_MIN_SPIN          1295
#define IDC_TUISLIDER_Label2            1296
#define IDC_TUISLIDER_MAX_SPIN          1297
#define IDC_TUIMAX_SPIN                 1297
#define IDC_TUISLIDER_MIN_EDIT          1298
#define IDC_TUIMIN_EDIT                 1298
#define IDC_TUISLIDER_Label3            1299
#define IDC_TUISLIDER_VALUE_SPIN        1300
#define IDC_TUIVALUE_SPIN               1300
#define IDC_TUISLIDER_Label4            1301
#define IDC_TUISLIDER_TICKS_SPIN        1302
#define IDC_TUIVAL_SPIN                 1302
#define IDC_TUIMIN_SPIN                 1312
#define IDC_COMBOBOXEX3                 1320
#define IDC_TREE1                       1326
#define IDC_TUISTYLE_COMBO              1327
#define IDC_TUIORIENTATION_SLIDER       1328
#define IDC_TUIEMPTY_CHECK              1330
#define IDC_TUIDEFAULT_COMBO            1332
#define IDC_TUIORIENTATION_SPLITTER     1333
#define IDC_TUIEMPTY_EDIT               1336
#define IDC_CAL_ICON_SIZE               1337
#define IDC_CAL_ICON_SIZE_SPINNER       1338
#define IDC_ANIMATION_EDIT              1339
#define IDC_ANIMATION_SPIN              1340
#define IDC_ACTION_EDIT2                1341
#define IDC_ACTION_SPIN2                1342
#define IDC_CAL_CFG_URL                 1345
#define IDC_ShaderUniformEDIT           1346
#define IDC_MAX_POLY_EDIT               1349
#define IDC_MAX_POLY_SPIN               1350
#define IDC_MAX_SELECTED_EDIT           1351
#define IDC_MAX_SELECTED_SPIN           1352
#define IDC_NEAR_EDIT                   1353
#define IDC_NEAR_SPIN                   1354
#define IDC_FAR_EDIT                    1355
#define IDC_FAR_SPIN                    1356
#define IDC_COVISEOOBJECT_URL           1357
#define IDC_COVISEOOBJECT_SIZE          1358
#define IDC_COVISEOOBJECT_SIZE_SPINNER  1359
#define IDC_COVISEOOBJECT_BBOX_SIZE     1360
#define IDC_COVISEOOBJECT_BBOX_DEF      1361
#ifndef _MSC_VER
#define _MSC_VER                        1900
#endif
#define IDS_PANELTITLE                  5012
#define IDS_TUIPARAM_EDITOR             5017
#define IDS_DS_CREATE                   10008
#define IDS_DS_EXCLUDE__                10122
#define IDS_DS_INCLUDE__                10123
#define IDS_DS_LIGHTCOL                 10175
#define IDS_DB_TDIST                    20072
#define IDS_DB_MULTIPLIER               20315
#define IDS_DB_ATTENSTART               20316
#define IDS_DB_ATTENEND                 20317
#define IDS_DB_HOTSIZE                  20318
#define IDS_DB_FALLSIZE                 20319
#define IDS_DB_COLOR                    20320
#define IDS_DB_ASPECT_RATIO             20323
#define IDS_DB_TAPE_LENGTH              20326
#define IDS_DB_NRANGE                   20453
#define IDS_DB_FRANGE                   20454
#define IDS_RB_OBJECT                   30004
#define IDS_RB_PARAMETERS               30028
#define IDS_RB_ANGLE                    30029
#define IDS_RB_AMOUNT                   30031
#define IDS_RB_RED                      30049
#define IDS_RB_GREEN                    30050
#define IDS_RB_BLUE                     30051
#define IDS_RB_HOTSIZE                  30052
#define IDS_RB_TRANSFORM                30053
#define IDS_RB_BASEPARAMS               30054
#define IDS_DB_TARGET                   30055
#define IDS_DB_DOT_TARGET               30056
#define IDS_DB_OMNI                     30057
#define IDS_DB_TARGET_SPOT              30058
#define IDS_DB_DIRECTIONAL              30059
#define IDS_DB_FREE_SPOT                30060
#define IDS_DB_NONE                     30061
#define IDS_DB_GENERAL_PARAMS           30064
#define IDS_DB_DIR_PARAMS               30065
#define IDS_DB_SPOT_PARAMS              30066
#define IDS_DB_SHADOW_PARAMS            30067
#define IDS_DB_SELECT_TO_FIT            30068
#define IDS_DB_OMNI_LIGHT               30069
#define IDS_DB_DIR_LIGHT                30070
#define IDS_DB_DIRECT                   30071
#define IDS_DB_FSPOT                    30072
#define IDS_DB_SPOT                     30073
#define IDS_DB_LIGHT                    30074
#define IDS_DB_TAPE                     30075
#define IDS_DB_GENERAL                  30076
#define IDS_RB_GEOMETERIC               30157
#define IDS_RB_SHAPES                   30158
#define IDS_RB_LIGHTS                   30159
#define IDS_RB_CPPOBJECTOUT             30619
#define IDS_RB_CPPFILES                 30620
#define IDS_RB_SAVEOBJECT               30621
#define IDS_RB_FILEEXISTS               30625
#define IDS_RB_MAPSIZE                  30640
#define IDS_RB_MAPBIAS                  30641
#define IDS_RB_MAPRANGE                 30642
#define IDS_RB_RAYBIAS                  30643
#define IDS_RB_NEARPLANE                30644
#define IDS_RB_FARPLANE                 30645
#define IDS_PRS_URL                     30646
#define IDS_PRS_DESCRIPTION             30647
#define IDS_SKY_COLORS                  30648
#define IDS_GROUND_COLORS               30649
#define IDS_IMAGES                      30650
#define IDS_MT_SENSOR                   30651
#define IDS_MT_SENSOR_CLASS             30652
#define IDS_MultiTouchSensor_PICK_MODE  30653
#define IDS_MT_SURFACE                  30654
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1347
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
