MACRO(USE_BIFBOF)
  COVISE_FIND_PACKAGE(BIFBOF)
  IF ((NOT BIFBOF_FOUND) AND (${ARGC} LESS 1))
    USING_MESSAGE("Skipping because of missing BIFBOF")
    RETURN()
  ENDIF((NOT BIFBOF_FOUND) AND (${ARGC} LESS 1))
  IF(NOT BIFBOF_USED AND BIFBOF_FOUND)
    SET(BIFBOF_USED TRUE)
    INCLUDE_DIRECTORIES(${BIFBOF_INCLUDE_DIR})
    SET(EXTRA_LIBS ${BIFBOF_LIBRARIES} ${EXTRA_LIBS})
  ENDIF()

ENDMACRO(USE_BIFBOF)

