MACRO(USE_CAVEUI)
  IF(NOT CAVEUI_USED)
    SET(CAVEUI_USED TRUE)
    #INCLUDE_DIRECTORIES(${CAVEUI_INCLUDE_DIR})
    SET(EXTRA_LIBS ${EXTRA_LIBS} osgcaveui)
  ENDIF(NOT CAVEUI_USED)
ENDMACRO(USE_CAVEUI)

