MACRO(USE_FORTRAN)
  if(NOT COVISE_USE_FORTRAN)
    return()
  endif()
  enable_language(Fortran OPTIONAL)
  if((NOT CMAKE_Fortran_COMPILER_WORKS) AND (${ARGC} LESS 1))
    using_message("Skipping because of missing Fortran compiler")
    return()
  endif()
  enable_language(Fortran)
ENDMACRO(USE_FORTRAN)
