MACRO(USE_OPENSCENEGRAPH)
    SET(OPENSCENEGRAPH_USED TRUE)
    INCLUDE_DIRECTORIES(SYSTEM ${OPENSCENEGRAPH_INCLUDE_DIRS})
	ADD_DEFINITIONS(-DHAVE_OPENSCENEGRAPH)
    SET(EXTRA_LIBS ${EXTRA_LIBS} ${OPENSCENEGRAPH_LIBRARIES})
ENDMACRO(USE_OPENSCENEGRAPH)

