MACRO(USE_OPENCRG)
    covise_find_package(OpenCRG)
    if ((NOT OPENCRG_FOUND) AND (${ARGC} LESS 1))
        using_message("Skipping because of missing OpenCRG")
        return()
    endif((NOT OPENCRG_FOUND) AND (${ARGC} LESS 1))
    if(NOT OPENCRG_USED AND OPENCRG_FOUND)
        set(OPENCRG_USED TRUE)
        include_directories(SYSTEM ${OPENCRG_INCLUDE_DIRS})
        set(EXTRA_LIBS ${EXTRA_LIBS} ${OPENCRG_LIBRARIES})
    endif()
ENDMACRO(USE_OPENCRG)
