MACRO(USE_OPENXR)
  IF ((NOT OPENXR_FOUND) AND (NOT TARGET OpenXR::openxr_loader) AND (${ARGC} LESS 1))
    USING_MESSAGE("Skipping because of missing OPENXR")
    RETURN()
  ENDIF()
  IF (OPENXR_FOUND AND NOT TARGET OpenXR::openxr_loader)
	  add_library(OpenXR::openxr_loader STATIC IMPORTED)
    set_target_properties(OpenXR::openxr_loader PROPERTIES
        IMPORTED_CONFIGURATIONS "DEBUG;RELEASE"
        IMPORTED_LOCATION_DEBUG "${OPENXR_LIBRARY_DEBUG}"
        IMPORTED_LOCATION_RELEASE "${OPENXR_LIBRARY}"
    )
  ENDIF()
  IF(NOT OPENXR_USED AND OPENXR_FOUND)
    SET(OPENXR_USED TRUE)
    ADD_DEFINITIONS(-DHAVE_OPENXR)
    INCLUDE_DIRECTORIES(SYSTEM ${OPENXR_INCLUDE_DIR})
    SET(EXTRA_LIBS ${EXTRA_LIBS} ${OPENXR_LIBRARIES})
  ENDIF()
ENDMACRO(USE_OPENXR)

