MACRO(USE_PTHREADS)
   if(MSVC OR MINGW)
      find_path(PTHREADW32_INCLUDE_DIR pthread.h PATHS "$ENV{EXTERNLIBS}/pthreads/include")

      if(MSVC)
         find_library(PTHREADW32_LIBRARY pthreadVC2.lib PATHS "$ENV{EXTERNLIBS}/pthreads/lib")
      else()
         find_library(PTHREADW32_LIBRARY pthread PATHS "$ENV{EXTERNLIBS}/pthreads/lib")
      endif()
      if(NOT PTHREADW32_INCLUDE_DIR OR NOT PTHREADW32_LIBRARY)
         using_message("Skipping pthread for Windows was not found!")
         return()
      endif()
      include_directories(${PTHREADW32_INCLUDE_DIR})
      set(EXTRA_LIBS ${PTHREADW32_LIBRARY} ${EXTRA_LIBS})
   else(MSVC OR MINGW)
      include_directories(${PTHREAD_INCLUDE_DIR})
      set(EXTRA_LIBS ${CMAKE_THREAD_LIBS_INIT} ${EXTRA_LIBS})
      set(EXTRA_LIBS ${PTHREAD_LIBRARY} ${EXTRA_LIBS})
   endif(MSVC OR MINGW)

   if(CMAKE_COMPILER_IS_GNUCXX OR "${CMAKE_CXX_COMPILER_ID}" MATCHES "Clang")
      if(MINGW)
         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mthreads")
      else()
         set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
      endif()
   endif()

   if(NOT PTHREADS_USED AND PTHREADS_FOUND)
      set(PTHREADS_USED TRUE)
   endif()
ENDMACRO(USE_PTHREADS)
