MACRO(USE_SPEEX)
  COVISE_FIND_PACKAGE(SPEEX)
  IF ((NOT SPEEX_FOUND) AND (${ARGC} LESS 1))
    USING_MESSAGE("Skipping because of missing SPEEX")
    RETURN()
  ENDIF((NOT SPEEX_FOUND) AND (${ARGC} LESS 1))
  IF(NOT SPEEX_USED AND SPEEX_FOUND)
    SET(SPEEX_USED TRUE)
    INCLUDE_DIRECTORIES(SYSTEM ${SPEEX_INCLUDE_DIR})
    SET(EXTRA_LIBS ${SPEEX_LIBRARIES} ${EXTRA_LIBS})
  ENDIF()

ENDMACRO(USE_SPEEX)

