MACRO(USE_SDL2)
    covise_find_package(sdl2)
    if ((NOT SDL2_INCLUDE_DIRS) AND (${ARGC} LESS 1))
        using_message("Skipping because of missing SDL2 includes")
        return()
    endif()
    if ((NOT SDL2_LIBRARIES) AND (${ARGC} LESS 1))
        using_message("Skipping because of missing SDL2 libraries")
        return()
    endif()
    if(NOT SDL2_USED AND SDL2_INCLUDE_DIRS AND SDL2_LIBRARIES)
        set(SDL2_USED TRUE)
        include_directories(SYSTEM ${SDL2_INCLUDE_DIRS})
        add_definitions(-DHAVE_SDL2)
        set(EXTRA_LIBS ${EXTRA_LIBS} ${SDL2_LIBRARIES})
    endif()
ENDMACRO(USE_SDL2)
