MACRO(USE_TRAFFICSIMULATION)
set(OPT "")
if ("${ARGN}" STREQUAL "optional")
    set(OPT "optional")
endif()

if(NOT COVISE_BUILD_DRIVINGSIM)
    if (NOT "${OPT}" STREQUAL "optional")
        return()
    endif()
else()
    if (NOT TRAFFICSIMULATION_USED)
        set(TRAFFICSIMULATION_USED TRUE)

        covise_find_package(OSGCAL)
        covise_find_package(CAL3D)
        covise_find_package(GDAL)
        covise_find_package(OpenSceneGraph 3.2.0 COMPONENTS osgTerrain)

        use_xercesc(${OPT})
        use_vehicleutil(${OPT})
        use_vrml(${OPT})
        use_osgcal(${OPT})

        if (NOT "${OPT}" STREQUAL "optional")
            if(NOT GDAL_FOUND)
                return()
            endif()
        endif()

        set(EXTRA_LIBS ${EXTRA_LIBS} coTrafficSimulation)
        include_directories(${COVISEDIR}/src/OpenCOVER/DrivingSim)
    endif()
endif()
ENDMACRO(USE_TRAFFICSIMULATION)
