MACRO(USE_VEHICLEUTIL)
set(OPT "")
if ("${ARGN}" STREQUAL "optional")
    set(OPT "optional")
endif()

if(NOT COVISE_BUILD_DRIVINGSIM)
    if (NOT "${OPT}" STREQUAL "optional")
        return()
    endif()
else()
    if (NOT VEHICLEUTIL_USED)
        set(VEHICLEUTIL_USED TRUE)
        use_proj4(${OPT})
        use_xercesc(${OPT})
        use_opencrg(${OPT})
        use_v8(optional)

        set(EXTRA_LIBS ${EXTRA_LIBS} coOpenVehicleUtil)
        include_directories(${COVISEDIR}/src/OpenCOVER/DrivingSim)
    endif()
endif()
ENDMACRO(USE_VEHICLEUTIL)
