MACRO(USE_VTK)
  IF ((NOT VTK_FOUND) AND (${ARGC} LESS 1))
    USING_MESSAGE("Skipping because of missing VTK")
    RETURN()
  ENDIF((NOT VTK_FOUND) AND (${ARGC} LESS 1))
  IF(NOT VTK_USED AND VTK_FOUND)
    SET(VTK_USED TRUE)
    add_definitions(-DHAVE_VTK)
    include_directories(SYSTEM ${VTK_INCLUDE_DIRS})
    set_property(DIRECTORY APPEND PROPERTY COMPILE_DEFINITIONS ${VTK_DEFINITIONS})
    IF(MSVC AND NOT BASEARCHSUFFIX STREQUAL "vcpkg" AND VTK_INCLUDE_DIRS)
      IF(BASEARCHSUFFIX STREQUAL "zebu")
        set(VTK_LIBRARY_VERSION -${VTK_MAJOR_VERSION}.${VTK_MINOR_VERSION})
        SET(VTK_LIBRARIES debug ${VTK_DIR}/../../vtkCommonDataModel${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkCommonDataModel${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkCommonExecutionModel${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkCommonExecutionModel${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkCommonCore${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkCommonCore${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkIOLegacy${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkIOLegacy${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkIOXML${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkIOXML${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkImagingCore${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkImagingCore${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkIOCore${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkIOCore${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkfreetype${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkfreetype${VTK_LIBRARY_VERSION}.lib general opengl32)
      ENDIF()
      SET(VTK_LIBRARIESIO debug ${VTK_DIR}/../../vtkFiltersCore${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkFiltersCore${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkDICOMParser${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkDICOMParser${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkNetCDF${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkNetCDF${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkmetaio${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkmetaio${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtksqlite${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtksqlite${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkpng${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkpng${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkzlib${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkzlib${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkjpeg${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkjpeg${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtktiff${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtktiff${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtkexpat${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkexpat${VTK_LIBRARY_VERSION}.lib debug ${VTK_DIR}/../../vtksys${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtksys${VTK_LIBRARY_VERSION}.lib general vfw32)
      
      SET(VTK_LIBRARIESFILTERING debug ${VTK_DIR}/../../vtkCommonCore${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtkCommonCore${VTK_LIBRARY_VERSION}.lib)
      SET(VTK_LIBRARIESCOMMON debug ${VTK_DIR}/../../vtksys${VTK_LIBRARY_VERSION}d.lib optimized ${VTK_DIR}/../../vtksys${VTK_LIBRARY_VERSION}.lib)
      SET(EXTRA_LIBS ${EXTRA_LIBS} ${VTK_LIBRARIES} ${VTK_LIBRARIESIO} ${VTK_LIBRARIESFILTERING} ${VTK_LIBRARIESCOMMON})
    ELSE()
      IF(MINGW)
          SET(EXTRA_LIBS ${EXTRA_LIBS} vtkCommon vtkGraphics vtkIO vtkFiltering)
      ELSE()
         set(EXTRA_LIBS ${EXTRA_LIBS} ${VTK_LIBRARIES})
      ENDIF()
      if (CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
         SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated")
      elseif (CMAKE_CXX_COMPILER_ID MATCHES "Clang")
         SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated -Wno-inconsistent-missing-override")
      endif()
    ENDIF(MSVC AND NOT BASEARCHSUFFIX STREQUAL "vcpkg")
  ENDIF()
ENDMACRO(USE_VTK)

