MACRO(USE_wiringPi)
  FIND_PACKAGE(wiringPi)
  IF ((NOT wiringPi_FOUND) AND (${ARGC} LESS 1))
    USING_MESSAGE("Skipping because of missing wiringPi")
    RETURN()
  ENDIF((NOT wiringPi_FOUND) AND (${ARGC} LESS 1))
  IF(NOT wiringPi_USED AND wiringPi_FOUND)
    SET(wiringPi_USED TRUE)
    INCLUDE_DIRECTORIES(${wiringPi_INCLUDE_DIR})
	ADD_DEFINITIONS(-DHAVE_WIRINGPI)
    SET(EXTRA_LIBS ${EXTRA_LIBS} ${wiringPi_LIBRARIES})
  ENDIF()
ENDMACRO(USE_wiringPi)

