#! /bin/csh

set VARLIST="XVID X11 MOTIF QT"
set VARLIST="${VARLIST} PERFORMER OGL GLUT OIV OSG"
set VARLIST="${VARLIST} TIFF PNG"
set VARLIST="${VARLIST} ESD IRIXAL AUDIOFILE OPENAL ALSA"
set VARLIST="${VARLIST} CG FLEXLM PYTHON PTHREAD TCL TK CAL3D ARTOOLKIT"
