#! /bin/bash

WARN="# -- everything below auto-generated by scripts/update-gitignore.sh --"

sed -e '/^# --.*--$/,$d' .gitignore > .gitignore.new \
    && echo "$WARN" >> .gitignore.new \
&& grep -h -E  -v  '(^#|^$)' README-ARCHSUFFIX.txt \
    | sed -e 's/^\([a-zA-Z0-9+]*\).*/\1\
\1opt/' >> .gitignore.new \
&& mv .gitignore.new .gitignore
