// C4D-DialogResource
DIALOG IDD_VRMLEXP_DLG
{
  NAME IDS_DIALOG; CENTER_V; CENTER_H; 
  
  STATICTEXT IDS_HEADLINE { NAME IDS_STATIC; CENTER_V; ALIGN_LEFT; }
  SEPARATOR { SCALE_H; }
  STATICTEXT IDC_STATICTEXT1 { NAME IDS_STATIC8; CENTER_V; ALIGN_LEFT; }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC12; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    COLUMNS 2;
    SPACE 4, 4;
    
    CHECKBOX IDC_CHECK_COPYTEXTURES { NAME IDS_CHECK_COPYTEXTURES; ALIGN_TOP; ALIGN_LEFT;  }
    COMBOBOX IDC_COMBO_TEXTUREEXPORT
    {
      ALIGN_TOP; ALIGN_LEFT; SIZE 150, 0; 
      CHILDS
      {
        IDC_REPLACEALL, IDS_REPLACEALL; 
        IDC_SKIPEXISTING, IDS_SKIPEXISTING; 
        IDC_ASKREPLACE, IDS_ASKREPLACE; 
      }
    }
  }
  CHECKBOX IDC_CHECK_SETTEXTUREDOBJECTCOLORWHITE { NAME IDS_CHECK_SETCOLORWHITE; ALIGN_TOP; ALIGN_LEFT;  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC10; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    ROWS 1;
    SPACE 4, 4;
    
    STATICTEXT IDC_AMBIENTINTENSITY { NAME IDS_STATIC9; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_EDIT_IDC_CHECK_AMBIENTINTENSITY
    { CENTER_V; ALIGN_RIGHT; SIZE 70, 0; }
  }
  SEPARATOR { SCALE_H; }
  CHECKBOX IDC_CHECK_EXPORTNORMALS { NAME IDS_CHECK3; ALIGN_TOP; ALIGN_LEFT;  }
  SEPARATOR { SCALE_H; }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC11; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    ROWS 1;
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC_TEXT_DATAFORMAT { NAME IDS_STATIC6; CENTER_V; ALIGN_LEFT; }
    COMBOBOX IDC_COMBO_DATAFORMAT
    {
      ALIGN_TOP; ALIGN_LEFT; SIZE 150, 0; 
      CHILDS
      {
        IDC_OPENCOVERVRMLMOD, IDS_OPENCOVERVRMLMOD; 
        IDC_NORMALVRML, IDS_NORMALVRML; 
      }
    }
  }
  SEPARATOR { SCALE_H; }
  STATICTEXT IDC_STATIC_TEXT_DONTEXPORTWHEN { NAME IDS_STATIC7; CENTER_V; ALIGN_LEFT; }
  CHECKBOX IDC_CHECK_VISIBILITYEDITOR { NAME IDS_CHECK_VISIBILITYEDITOR; ALIGN_TOP; ALIGN_LEFT;  }
  CHECKBOX IDC_CHECK_VISIBILITYRENDER { NAME IDS_CHECK_VISIBILITYRENDER; ALIGN_TOP; ALIGN_LEFT;  }
  SEPARATOR { SCALE_H; }
  STATICTEXT IDC_STATIC_TEXT_ANIMATION { NAME IDS_STATIC13; CENTER_V; ALIGN_LEFT; }
  CHECKBOX IDC_CHECK_WRITEANIMATION { NAME IDS_CHECK2; ALIGN_TOP; ALIGN_LEFT;  }
  GROUP IDC_STATIC
  {
    NAME IDS_STATIC14; ALIGN_TOP; ALIGN_LEFT; 
    BORDERSIZE 0, 0, 0, 0; 
    SPACE 4, 4;
    
    STATICTEXT IDC_STATIC_NOOFKEYFRAMES { NAME IDS_STATIC16; CENTER_V; ALIGN_LEFT; }
    EDITNUMBERARROWS IDC_EDIT1_NOOFKEYFRAMES
    { CENTER_V; CENTER_H; SIZE 70, 0; }
  }
  SEPARATOR { SCALE_H; }
  DLGGROUP { OK; CANCEL; }
}