default: 
	doxygen Doxyfile.txt
	@echo ======================================================
	@echo Done! Load html/index.html with your browser.
	@echo ======================================================

clean:
	rm -rf html
