# - Find EXPRTK
# Find the EXPRTK includes and library
#
#  EXPRTK_INCLUDE_DIR - Where to find EXPRTK includes
#  EXPRTK_LIBRARIES   - List of libraries when using EXPRTK
#  EXPRTK_FOUND       - True if EXPRTK was found

IF(EXPRTK_INCLUDE_DIR)
  SET(EXPRTK_FIND_QUIETLY TRUE)
ENDIF(EXPRTK_INCLUDE_DIR)

FIND_PATH(EXPRTK_INCLUDE_DIR "exprtk.hpp"
  PATHS
  $ENV{EXTERNLIBS}/exprtk
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  PATH_SUFFIXES  include
  DOC "EXPRTK - Headers"
)

INCLUDE(FindPackageHandleStandardArgs)

IF(MSVC)
 

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(EXPRTK DEFAULT_MSG EXPRTK_INCLUDE_DIR)

  MARK_AS_ADVANCED( EXPRTK_INCLUDE_DIR)
  
ELSE(MSVC)

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(EXPRTK DEFAULT_MSG EXPRTK_INCLUDE_DIR)
  
  MARK_AS_ADVANCED(EXPRTK_INCLUDE_DIR)
  
ENDIF(MSVC)

IF(EXPRTK_FOUND)
  SET(EXPRTK_INCLUDE_DIRS ${EXPRTK_INCLUDE_DIR})
ENDIF(EXPRTK_FOUND)
