# - Try to find ossimplanet-library
# Once done this will define
#
#  OSSIMPLANET_INCLUDE_DIR    - where to find ossimplanet.h
#  OSSIMPLANET_INCLUDE_DIRS   - same as above (uncached version)
#  OSSIMPLANET_LIBRARIES      - list of libraries when using ossimplanet
#  OSSIMPLANET_FOUND          - True if ossimplanet was found.


IF(OSSIMPLANET_INCLUDE_DIR)
  SET(OSSIMPLANET_FIND_QUIETLY TRUE)
ENDIF(OSSIMPLANET_INCLUDE_DIR)

FIND_PATH(OSSIMPLANET_INCLUDE_DIR "ossim/ossimConfig.h"
  PATHS
  $ENV{OSSIMPLANET_HOME}/include
  $ENV{EXTERNLIBS}/ossim/include
  ~/Library/Frameworks/include
  /Library/Frameworks/include
  /usr/local/include
  /usr/include
  /sw/include # Fink
  /opt/local/include # DarwinPorts
  /opt/csw/include # Blastwave
  /opt/include
  DOC "OSSIMPLANET - Headers"
)

SET(OSSIM_NAMES ossim )
SET(OSSIM_DBG_NAMES ossimD)

FIND_LIBRARY(OSSIM_LIBRARY NAMES ${OSSIM_NAMES}
  PATHS
  $ENV{OSSIMPLANET_HOME}
  $ENV{EXTERNLIBS}/ossimplanet
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "OSSIMPLANET - Library"
)

SET(OSSIMPLANET_NAMES ossimPlanet )
SET(OSSIMPLANET_DBG_NAMES ossimPlanetD)

FIND_LIBRARY(OSSIMPLANET_LIBRARY NAMES ${OSSIMPLANET_NAMES}
  PATHS
  $ENV{OSSIMPLANET_HOME}
  $ENV{EXTERNLIBS}/ossimplanet
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "OSSIMPLANET - Library"
)

INCLUDE(FindPackageHandleStandardArgs)

IF(MSVC)
  # VisualStudio needs a debug version
  FIND_LIBRARY(OSSIMPLANET_LIBRARY_DEBUG NAMES ${OSSIMPLANET_DBG_NAMES}
    PATHS
    $ENV{OSSIMPLANET_HOME}/lib
    $ENV{EXTERNLIBS}/ossim/lib
    DOC "OSSIMPLANET - Library (Debug)"
  )
  
  FIND_LIBRARY(OSSIM_LIBRARY_DEBUG NAMES ${OSSIM_DBG_NAMES}
    PATHS
    $ENV{OSSIMPLANET_HOME}/lib
    $ENV{EXTERNLIBS}/ossim/lib
    DOC "OSSIMPLANET - Library (Debug)"
  )
  
  IF(OSSIMPLANET_LIBRARY_DEBUG AND OSSIMPLANET_LIBRARY)
    SET(OSSIMPLANET_LIBRARIES optimized ${OSSIMPLANET_LIBRARY} debug ${OSSIMPLANET_LIBRARY_DEBUG})
  ENDIF(OSSIMPLANET_LIBRARY_DEBUG AND OSSIMPLANET_LIBRARY)
  
  IF(OSSIM_LIBRARY_DEBUG AND OSSIM_LIBRARY)
    SET(OSSIMPLANET_LIBRARIES ${OSSIMPLANET_LIBRARIES} optimized ${OSSIM_LIBRARY} debug ${OSSIM_LIBRARY_DEBUG})
  ENDIF(OSSIM_LIBRARY_DEBUG AND OSSIM_LIBRARY)

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSSIMPLANET DEFAULT_MSG OSSIMPLANET_LIBRARY OSSIMPLANET_LIBRARY_DEBUG OSSIM_LIBRARY OSSIM_LIBRARY_DEBUG OSSIMPLANET_INCLUDE_DIR)

  MARK_AS_ADVANCED(OSSIMPLANET_LIBRARY OSSIMPLANET_LIBRARY_DEBUG OSSIM_LIBRARY OSSIM_LIBRARY_DEBUG OSSIMPLANET_INCLUDE_DIR)
  
ELSE(MSVC)
  # rest of the world
  SET(OSSIMPLANET_LIBRARIES ${OSSIMPLANET_LIBRARY} ${OSSIM_LIBRARY})

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSSIMPLANET DEFAULT_MSG OSSIMPLANET_LIBRARY  OSSIM_LIBRARY OSSIMPLANET_INCLUDE_DIR)
  
  MARK_AS_ADVANCED(OSSIMPLANET_LIBRARY OSSIM_LIBRARY OSSIMPLANET_INCLUDE_DIR)
  
ENDIF(MSVC)

IF(OSSIMPLANET_FOUND)
  SET(OSSIMPLANET_INCLUDE_DIRS ${OSSIMPLANET_INCLUDE_DIR})
ENDIF(OSSIMPLANET_FOUND)
