# - Find CFX
# Find the CFX includes and library
#
#  CFX_INCLUDE_DIR - Where to find CFX includes
#  CFX_LIBRARIES   - List of libraries when using CFX
#  CFX_FOUND       - True if CFX was found

IF(CFX_INCLUDE_DIR)
    SET(CFX_FIND_QUIETLY TRUE)
ENDIF(CFX_INCLUDE_DIR)

FIND_PATH(CFX_DIR NAMES "include/cfxExport.h"
    PATHS
    $ENV{EXTERNLIBS}/CFX-17
    $ENV{EXTERNLIBS}/CFX-162
    $ENV{EXTERNLIBS}/CFX-15
    $ENV{EXTERNLIBS}/CFX-14
    $ENV{EXTERNLIBS}/CFX-12
    DOC "CFX installation directory"
)

FIND_PATH(CFX_INCLUDE_DIR NAMES "cfxExport.h"
    PATHS ${CFX_DIR}/include
    DOC "CFX - header"
)


FIND_LIBRARY(CFX_IMPORT_LIBRARY NAMES "libmeshimport.a" "libmeshimport.lib"
    PATHS ${CFX_DIR}/lib
)
FIND_LIBRARY(CFX_EXPORT_LIBRARY NAMES "libmeshexport.a" "libmeshexport.lib"
    PATHS ${CFX_DIR}/lib
)
FIND_LIBRARY(CFX_PGT_LIBRARY NAMES "libpgtapi.a" "libpgtapi.lib"
    PATHS ${CFX_DIR}/lib
)
FIND_LIBRARY(CFX_UNITS_LIBRARY NAMES "libunits.a" "libunits.lib"
    PATHS ${CFX_DIR}/lib
)
FIND_LIBRARY(CFX_CCLAPILT_LIBRARY NAMES "libcclapilt.a" "libcclapilt.lib"
    PATHS ${CFX_DIR}/lib
)
FIND_LIBRARY(CFX_IO_LIBRARY NAMES "libio.a" "libio.lib"
    PATHS ${CFX_DIR}/lib
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CFX DEFAULT_MSG CFX_DIR CFX_IMPORT_LIBRARY CFX_EXPORT_LIBRARY CFX_PGT_LIBRARY CFX_UNITS_LIBRARY CFX_CCLAPILT_LIBRARY CFX_IO_LIBRARY CFX_INCLUDE_DIR)
MARK_AS_ADVANCED(CFX_LIBRARY CFX_INCLUDE_DIR)

IF(CFX_FOUND)
    SET(CFX_LIBRARIES ${CFX_IMPORT_LIBRARY} ${CFX_EXPORT_LIBRARY} ${CFX_PGT_LIBRARY} ${CFX_UNITS_LIBRARY} ${CFX_CCLAPILT_LIBRARY} ${CFX_IO_LIBRARY})
    SET(CFX_INCLUDE_DIRS ${CFX_INCLUDE_DIR})
ENDIF(CFX_FOUND)
