# - Find CFX
# Find the CFX includes and library
#
#  CFX_INCLUDE_DIR - Where to find CFX includes
#  CFX_LIBRARIES   - List of libraries when using CFX
#  CFX_FOUND       - True if CFX was found

IF(CFX_INCLUDE_DIR)
  SET(CFX_FIND_QUIETLY TRUE)
ENDIF(CFX_INCLUDE_DIR)

FIND_PATH(CFX_INCLUDE_DIR NAMES "cfxExport.h"
  PATHS
  $ENV{EXTERNLIBS}/CFX-15/include
  $ENV{EXTERNLIBS}/CFX-14/include
  $ENV{EXTERNLIBS}/CFX-12/include
  DOC "CFX - Headers"
)

FIND_LIBRARY(CFX_IMPORT_LIBRARY NAMES "libmeshimport.a" "libmeshimport.lib"
  PATHS
  $ENV{EXTERNLIBS}/CFX-15/lib
  $ENV{EXTERNLIBS}/CFX-14/lib
  $ENV{EXTERNLIBS}/CFX-12/lib
)
FIND_LIBRARY(CFX_EXPORT_LIBRARY NAMES "libmeshexport.a" "libmeshexport.lib"
  PATHS
  $ENV{EXTERNLIBS}/CFX-15/lib
  $ENV{EXTERNLIBS}/CFX-14/lib
  $ENV{EXTERNLIBS}/CFX-12/lib
)
FIND_LIBRARY(CFX_PGT_LIBRARY NAMES "libpgtapi.a" "libpgtapi.lib"
  PATHS
  $ENV{EXTERNLIBS}/CFX-15/lib
  $ENV{EXTERNLIBS}/CFX-14/lib
  $ENV{EXTERNLIBS}/CFX-12/lib
)
FIND_LIBRARY(CFX_UNITS_LIBRARY NAMES "libunits.a" "libunits.lib"
  PATHS
  $ENV{EXTERNLIBS}/CFX-15/lib
  $ENV{EXTERNLIBS}/CFX-14/lib
  $ENV{EXTERNLIBS}/CFX-12/lib
)
FIND_LIBRARY(CFX_CCLAPILT_LIBRARY NAMES "libcclapilt.a" "libcclapilt.lib"
  PATHS
  $ENV{EXTERNLIBS}/CFX-15/lib
  $ENV{EXTERNLIBS}/CFX-14/lib
  $ENV{EXTERNLIBS}/CFX-12/lib
)
FIND_LIBRARY(CFX_IO_LIBRARY NAMES "libio.a" "libio.lib"
  PATHS
  $ENV{EXTERNLIBS}/CFX-15/lib
  $ENV{EXTERNLIBS}/CFX-14/lib
  $ENV{EXTERNLIBS}/CFX-12/lib
)

INCLUDE(FindPackageHandleStandardArgs)

SET(CFX_LIBRARIES ${CFX_IMPORT_LIBRARY} ${CFX_EXPORT_LIBRARY} ${CFX_PGT_LIBRARY} ${CFX_UNITS_LIBRARY} ${CFX_CCLAPILT_LIBRARY} ${CFX_IO_LIBRARY})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CFX DEFAULT_MSG CFX_IMPORT_LIBRARY CFX_EXPORT_LIBRARY CFX_PGT_LIBRARY CFX_UNITS_LIBRARY CFX_CCLAPILT_LIBRARY CFX_IO_LIBRARY CFX_INCLUDE_DIR)
MARK_AS_ADVANCED(CFX_LIBRARY CFX_INCLUDE_DIR)

IF(CFX_FOUND)
  SET(CFX_INCLUDE_DIRS ${CFX_INCLUDE_DIR})
ENDIF(CFX_FOUND)
