# - Find WIIYOURSELF
# Find the WIIYOURSELF includes and library
#
#  WIIYOURSELF_INCLUDE_DIR - Where to find WIIYOURSELF includes
#  WIIYOURSELF_LIBRARIES   - List of libraries when using WIIYOURSELF
#  WIIYOURSELF_FOUND       - True if WIIYOURSELF was found

IF(WIIYOURSELF_INCLUDE_DIR)
  SET(WIIYOURSELF_FIND_QUIETLY TRUE)
ENDIF(WIIYOURSELF_INCLUDE_DIR)

FIND_PATH(WIIYOURSELF_INCLUDE_DIR "wiimote_state.h"
  PATHS
  $ENV{EXTERNLIBS}/WiiYourself/include
  ~/Library/Frameworks/include
  /Library/Frameworks/include
  /usr/local/include
  /usr/include
  /sw/include # Fink
  /opt/local/include # DarwinPorts
  /opt/csw/include # Blastwave
  /opt/include
  DOC "WIIYOURSELF - Headers"
)

SET(WIIYOURSELF_NAMES WiiYourselfS)
SET(WIIYOURSELF_DBG_NAMES WiiYourselfSD)
SET(WIIYOURSELF_HID_NAMES hid)

FIND_LIBRARY(WIIYOURSELF_LIBRARY NAMES ${WIIYOURSELF_NAMES}
  PATHS
  $ENV{EXTERNLIBS}/WiiYourself
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "WIIYOURSELF - Library"
)

FIND_LIBRARY(WIIYOURSELF_HID_LIBRARY NAMES hid}
  PATHS
  $ENV{EXTERNLIBS}/WiiYourself
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "WIIYOURSELF - Library"
)
FIND_LIBRARY(WIIYOURSELF_HID_LIBRARY NAMES ${WIIYOURSELF_HID_NAMES}
    PATHS
    $ENV{EXTERNLIBS}/WiiYourself/lib
    DOC "WIIYOURSELF - HID Library"
  )

INCLUDE(FindPackageHandleStandardArgs)

IF(MSVC)
  # VisualStudio needs a debug version
  FIND_LIBRARY(WIIYOURSELF_LIBRARY_DEBUG NAMES ${WIIYOURSELF_DBG_NAMES}
    PATHS
    $ENV{EXTERNLIBS}/WiiYourself/lib
    DOC "WIIYOURSELF - Library (Debug)"
  )
  
  IF(WIIYOURSELF_LIBRARY_DEBUG AND WIIYOURSELF_LIBRARY)
    SET(WIIYOURSELF_LIBRARIES optimized ${WIIYOURSELF_LIBRARY} debug ${WIIYOURSELF_LIBRARY_DEBUG} optimized ${WIIYOURSELF_HID_LIBRARY} debug ${WIIYOURSELF_HID_LIBRARY})
  ENDIF(WIIYOURSELF_LIBRARY_DEBUG AND WIIYOURSELF_LIBRARY)

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(WIIYOURSELF DEFAULT_MSG WIIYOURSELF_LIBRARY WIIYOURSELF_HID_LIBRARY WIIYOURSELF_LIBRARY_DEBUG WIIYOURSELF_INCLUDE_DIR)

  MARK_AS_ADVANCED(WIIYOURSELF_LIBRARY WIIYOURSELF_LIBRARY_DEBUG WIIYOURSELF_HID_LIBRARY WIIYOURSELF_INCLUDE_DIR)
  
ELSE(MSVC)
  # rest of the world
  SET(WIIYOURSELF_LIBRARIES ${WIIYOURSELF_LIBRARY})

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(WIIYOURSELF DEFAULT_MSG WIIYOURSELF_LIBRARY WIIYOURSELF_INCLUDE_DIR)
  
  MARK_AS_ADVANCED(WIIYOURSELF_LIBRARY WIIYOURSELF_INCLUDE_DIR)
  
ENDIF(MSVC)

IF(WIIYOURSELF_FOUND)
  SET(WIIYOURSELF_INCLUDE_DIRS ${WIIYOURSELF_INCLUDE_DIR})
ENDIF(WIIYOURSELF_FOUND)
