# - Find PHYSX
# Find the PHYSX includes and library
#
#  PHYSX_INCLUDE_DIR - Where to find PHYSX includes
#  PHYSX_LIBRARIES   - List of libraries when using PHYSX
#  PHYSX_FOUND       - True if PHYSX was found

IF(PHYSX_INCLUDE_DIR)
  SET(PHYSX_FIND_QUIETLY TRUE)
ENDIF(PHYSX_INCLUDE_DIR)

FIND_PATH(PHYSX_INCLUDE_DIR "PxPhysicsAPI.h"
  PATHS
  $ENV{PHYSX_HOME}/include
  $ENV{EXTERNLIBS}/PhysX/include
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
  /opt
  DOC "PHYSX - Headers"
)

SET(PHYSX_NAMES PhysX3_x64 PhysX3)
SET(PHYSX_DBG_NAMES PhysX3DEBUG_x64 PhysX3DEBUG)
SET(PHYSX_LL_NAMES LowLevel)
SET(PHYSX_LL_DBG_NAMES LowLevelDEBUG)
SET(PHYSX_COMMON_NAMES PhysX3Common_x64 PhysX3Common)
SET(PHYSX_COMMON_DBG_NAMES PhysX3CommonDEBUG_x64 PhysX3CommonDEBUG)
SET(PHYSX_EXTENSIONS_NAMES PhysX3Extensions)
SET(PHYSX_EXTENSIONS_DBG_NAMES PhysX3ExtensionsDEBUG)
SET(PHYSX_VD_NAMES PhysXVisualDebuggerSDK)
SET(PHYSX_VD_DBG_NAMES PhysXVisualDebuggerSDKDEBUG)
SET(PHYSX_COOKING_NAMES PhysX3Cooking_x64 PhysX3Cooking)
SET(PHYSX_COOKING_DBG_NAMES PhysX3CookingDEBUG_x64 PhysX3CookingDEBUG)

FIND_LIBRARY(PHYSX_LIBRARY NAMES ${PHYSX_NAMES}
  PATHS
  $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "PHYSX - Library"
)
FIND_LIBRARY(PHYSX_LL_LIBRARY NAMES ${PHYSX_LL_NAMES}
  PATHS
  $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "PHYSX_LL - Library"
)
FIND_LIBRARY(PHYSX_COMMON_LIBRARY NAMES ${PHYSX_COMMON_NAMES}
  PATHS
  $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "PHYSX_COMMON - Library"
)
FIND_LIBRARY(PHYSX_EXTENSIONS_LIBRARY NAMES ${PHYSX_EXTENSIONS_NAMES}
  PATHS
  $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "PHYSX_EXTENSIONS - Library"
)
FIND_LIBRARY(PHYSX_VD_LIBRARY NAMES ${PHYSX_VD_NAMES}
  PATHS
  $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "PHYSX_VD - Library"
)
FIND_LIBRARY(PHYSX_COOKING_LIBRARY NAMES ${PHYSX_COOKING_NAMES}
  PATHS
  $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "PHYSX_COOKING - Library"
)

INCLUDE(FindPackageHandleStandardArgs)

IF(MSVC)
  # VisualStudio needs a debug version
  FIND_LIBRARY(PHYSX_LIBRARY_DEBUG NAMES ${PHYSX_DBG_NAMES}
    PATHS
    $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
    PATH_SUFFIXES lib lib64
    DOC "PHYSX - Library (Debug)"
  )
  FIND_LIBRARY(PHYSX_LL_LIBRARY_DEBUG NAMES ${PHYSX_LL_DBG_NAMES}
    PATHS
    $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
    PATH_SUFFIXES lib lib64
    DOC "PHYSX_LL - Library (Debug)"
  )
  FIND_LIBRARY(PHYSX_COMMON_LIBRARY_DEBUG NAMES ${PHYSX_COMMON_DBG_NAMES}
    PATHS
    $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
    PATH_SUFFIXES lib lib64
    DOC "PHYSX_COMMON - Library (Debug)"
  )
  FIND_LIBRARY(PHYSX_EXTENSIONS_LIBRARY_DEBUG NAMES ${PHYSX_EXTENSIONS_DBG_NAMES}
    PATHS
    $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
    PATH_SUFFIXES lib lib64
    DOC "PHYSX_EXTENSIONS - Library (Debug)"
  )
  FIND_LIBRARY(PHYSX_VD_LIBRARY_DEBUG NAMES ${PHYSX_VD_DBG_NAMES}
    PATHS
    $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
    PATH_SUFFIXES lib lib64
    DOC "PHYSX_VD - Library (Debug)"
  )
  FIND_LIBRARY(PHYSX_COOKING_LIBRARY_DEBUG NAMES ${PHYSX_COOKING_DBG_NAMES}
    PATHS
    $ENV{PHYSX_HOME}
  $ENV{EXTERNLIBS}/PhysX/Lib/vc11win64
  $ENV{EXTERNLIBS}/PhysX/lib/
    PATH_SUFFIXES lib lib64
    DOC "PHYSX_COOKING - Library (Debug)"
  )
  
  
  IF(PHYSX_LIBRARY_DEBUG AND PHYSX_LIBRARY)
    SET(PHYSX_LIBRARIES optimized ${PHYSX_LIBRARY} debug ${PHYSX_LIBRARY_DEBUG} optimized ${PHYSX_LL_LIBRARY} debug ${PHYSX_LL_LIBRARY_DEBUG} optimized ${PHYSX_COMMON_LIBRARY} debug ${PHYSX_COMMON_LIBRARY_DEBUG} optimized ${PHYSX_EXTENSIONS_LIBRARY} debug ${PHYSX_EXTENSIONS_LIBRARY_DEBUG} optimized ${PHYSX_VD_LIBRARY} debug ${PHYSX_VD_LIBRARY_DEBUG} optimized ${PHYSX_COOKING_LIBRARY} debug ${PHYSX_COOKING_LIBRARY_DEBUG})
  ENDIF(PHYSX_LIBRARY_DEBUG AND PHYSX_LIBRARY)

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(PHYSX DEFAULT_MSG PHYSX_LIBRARY PHYSX_LIBRARY_DEBUG PHYSX_LL_LIBRARY PHYSX_LL_LIBRARY_DEBUG PHYSX_COMMON_LIBRARY PHYSX_COMMON_LIBRARY_DEBUG PHYSX_EXTENSIONS_LIBRARY PHYSX_EXTENSIONS_LIBRARY_DEBUG PHYSX_VD_LIBRARY PHYSX_VD_LIBRARY_DEBUG PHYSX_COOKING_LIBRARY PHYSX_COOKING_LIBRARY_DEBUG PHYSX_INCLUDE_DIR)

  MARK_AS_ADVANCED(PHYSX_LIBRARY PHYSX_LIBRARY_DEBUG PHYSX_LL_LIBRARY PHYSX_LL_LIBRARY_DEBUG PHYSX_COMMON_LIBRARY PHYSX_COMMON_LIBRARY_DEBUG PHYSX_EXTENSIONS_LIBRARY PHYSX_EXTENSIONS_LIBRARY_DEBUG PHYSX_VD_LIBRARY PHYSX_VD_LIBRARY_DEBUG PHYSX_COOKING_LIBRARY PHYSX_COOKING_LIBRARY_DEBUG PHYSX_INCLUDE_DIR)
  
ELSE(MSVC)
  # rest of the world
  SET(PHYSX_LIBRARIES ${PHYSX_LIBRARY} ${PHYSX_LL_LIBRARY} ${PHYSX_COMMON_LIBRARY} ${PHYSX_EXTENSIONS_LIBRARY} ${PHYSX_VD_LIBRARY} ${PHYSX_COOKING_LIBRARY})

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(PHYSX DEFAULT_MSG PHYSX_LIBRARY PHYSX_LL_LIBRARY PHYSX_COMMON_LIBRARY PHYSX_EXTENSIONS_LIBRARY PHYSX_VD_LIBRARY PHYSX_COOKING_LIBRARY PHYSX_INCLUDE_DIR)
  
  MARK_AS_ADVANCED(PHYSX_LIBRARY PHYSX_LL_LIBRARY PHYSX_COMMON_LIBRARY PHYSX_EXTENSIONS_LIBRARY PHYSX_VD_LIBRARY PHYSX_COOKING_LIBRARY PHYSX_INCLUDE_DIR)
  
ENDIF(MSVC)

IF(PHYSX_FOUND)
  SET(PHYSX_INCLUDE_DIRS ${PHYSX_INCLUDE_DIR})
ENDIF(PHYSX_FOUND)
