IF(PTHREAD_INCLUDE_DIR)
  SET(PTHREAD_FIND_QUIETLY TRUE)
ENDIF(PTHREAD_INCLUDE_DIR)


FIND_PATH(PTHREAD_INCLUDE_DIR pthread.h
   PATHS
   $ENV{PTHREAD_HOME}/include
   $ENV{EXTERNLIBS}/pthread/include
   $ENV{EXTERNLIBS}/pthreads/include
   /usr/include
   DOC "The directory where pthread.h resides"
)
MARK_AS_ADVANCED(PTHREAD_INCLUDE_DIR)

IF (MSVC)
    
      FIND_LIBRARY(PTHREAD_LIBRARY_DEBUG NAMES pthreadVC2d.lib
        PATHS
        $ENV{PTHREAD_HOME}/lib
        $ENV{EXTERNLIBS}/pthreads/lib
      )
      FIND_LIBRARY(PTHREAD_LIBRARY_RELEASE NAMES pthreadVC2.lib
        PATHS
        $ENV{PTHREAD_HOME}/lib
        $ENV{EXTERNLIBS}/pthreads/lib
      )
      IF (PTHREAD_LIBRARY_DEBUG AND PTHREAD_LIBRARY_RELEASE)
         SET(PTHREAD_LIBRARIES optimized ${PTHREAD_LIBRARY_RELEASE} debug ${PTHREAD_LIBRARY_DEBUG})
      ELSE (PTHREAD_LIBRARY_DEBUG AND PTHREAD_LIBRARY_RELEASE)
         SET(PTHREAD_LIBRARIES NOTFOUND)
         MESSAGE(STATUS "Could not find the debug AND release version of pthreads lib")
      ENDIF (PTHREAD_LIBRARY_DEBUG AND PTHREAD_LIBRARY_RELEASE)
    MARK_AS_ADVANCED(PTHREAD_LIBRARY_DEBUG PTHREAD_LIBRARY_RELEASE)
    

ELSE (MSVC)
  
  SET(PTHREAD_NAMES ${PTHREAD_NAMES} pthread)
  FIND_LIBRARY(PTHREAD_LIBRARY NAMES ${PTHREAD_NAMES}
    PATHS
    $ENV{PTHREAD_HOME}/lib
    $ENV{EXTERNLIBS}/pthread/lib
    $ENV{EXTERNLIBS}/pthreads/lib
    /usr/lib
    /usr/lib32
    /usr/lib64
    /usr/local/lib
    /opt/local/lib
    DOC "The pthread library"
  )
  FIND_LIBRARY(PTHREAD_LIBRARY NAMES ${PTHREAD_NAMES})

  IF (PTHREAD_LIBRARY)
    SET(PTHREAD_LIBRARIES ${PTHREAD_LIBRARY})
  ELSE (PTHREAD_LIBRARY)
    SET(PTHREAD_LIBRARIES NOTFOUND)
    MESSAGE(STATUS "Could not find pthread-library")    
  ENDIF (PTHREAD_LIBRARY)
  MARK_AS_ADVANCED(PTHREAD_LIBRARY)
  
ENDIF (MSVC)

INCLUDE(FindPackageHandleStandardArgs)

IF(MSVC)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(PTHREAD DEFAULT_MSG PTHREAD_LIBRARY_RELEASE PTHREAD_LIBRARY_DEBUG PTHREAD_INCLUDE_DIR)
  MARK_AS_ADVANCED(PTHREAD_LIBRARY_RELEASE PTHREAD_LIBRARY_DEBUG)
ELSE(MSVC)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(PTHREAD DEFAULT_MSG PTHREAD_LIBRARY PTHREAD_INCLUDE_DIR)
  MARK_AS_ADVANCED(PTHREAD_LIBRARY)
ENDIF(MSVC)
