# - Find osgCal
# Find the alut includes and library
#
#  OSGPHYSX_INCLUDE_DIR - Where to find OSGPHYSX includes
#  OSGPHYSX_LIBRARIES   - List of libraries when using OSGPHYSX
#  OSGPHYSX_FOUND       - True if OSGPHYSX was found

IF(OSGPHYSX_INCLUDE_DIR)
  SET(OSGPHYSX_FIND_QUIETLY TRUE)
ENDIF(OSGPHYSX_INCLUDE_DIR)

FIND_PATH(OSGPHYSX_INCLUDE_DIR "physics/PhysicsUtil.h"
  PATHS
  $ENV{OSGPHYSX_HOME}/include
  $ENV{EXTERNLIBS}/osgPhysX/include
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
  /opt
  DOC "OSGPHYSX - Headers"
)

SET(OSGPHYSX_NAMES osgPhysics)
SET(OSGPHYSX_DBG_NAMES osgPhysicsd)
SET(OSGPHYSX_UTILS_NAMES osgPhysicsUtils)
SET(OSGPHYSX_UTILS_DBG_NAMES osgPhysicsUtilsd)

FIND_LIBRARY(OSGPHYSX_LIBRARY NAMES ${OSGPHYSX_NAMES}
  PATHS
  $ENV{OSGPHYSX_HOME}
  $ENV{EXTERNLIBS}/osgPhysX
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "OSGPHYSX - Library"
)
FIND_LIBRARY(OSGPHYSX_UTILS_LIBRARY NAMES ${OSGPHYSX_UTILS_NAMES}
  PATHS
  $ENV{OSGPHYSX_HOME}
  $ENV{EXTERNLIBS}/osgPhysX
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "OSGPHYSX_UTILS - Library"
)

INCLUDE(FindPackageHandleStandardArgs)

IF(MSVC)
  # VisualStudio needs a debug version
  FIND_LIBRARY(OSGPHYSX_LIBRARY_DEBUG NAMES ${OSGPHYSX_DBG_NAMES}
    PATHS
    $ENV{OSGPHYSX_HOME}/lib
    $ENV{EXTERNLIBS}/osgPhysX/lib
    DOC "OSGPHYSX - Library (Debug)"
  )
  FIND_LIBRARY(OSGPHYSX_UTILS_LIBRARY_DEBUG NAMES ${OSGPHYSX_UTILS_DBG_NAMES}
    PATHS
    $ENV{OSGPHYSX_HOME}/lib
    $ENV{EXTERNLIBS}/osgPhysX/lib
    DOC "OSGPHYSX_UTILS - Library (Debug)"
  )
  
  IF(OSGPHYSX_LIBRARY_DEBUG AND OSGPHYSX_LIBRARY)
    SET(OSGPHYSX_LIBRARIES optimized ${OSGPHYSX_LIBRARY} debug ${OSGPHYSX_LIBRARY_DEBUG} optimized ${OSGPHYSX_UTILS_LIBRARY} debug ${OSGPHYSX_UTILS_LIBRARY_DEBUG} )
  ENDIF(OSGPHYSX_LIBRARY_DEBUG AND OSGPHYSX_LIBRARY)

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSGPHYSX DEFAULT_MSG OSGPHYSX_LIBRARY OSGPHYSX_LIBRARY_DEBUG OSGPHYSX_UTILS_LIBRARY OSGPHYSX_UTILS_LIBRARY_DEBUG OSGPHYSX_INCLUDE_DIR)

  MARK_AS_ADVANCED(OSGPHYSX_LIBRARY OSGPHYSX_LIBRARY_DEBUG OSGPHYSX_UTILS_LIBRARY OSGPHYSX_UTILS_LIBRARY_DEBUG OSGPHYSX_INCLUDE_DIR)
  
ELSE(MSVC)
  # rest of the world
  SET(OSGPHYSX_LIBRARIES ${OSGPHYSX_LIBRARY} ${OSGPHYSX_UTILS_LIBRARY} )

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OSGPHYSX DEFAULT_MSG OSGPHYSX_LIBRARY OSGPHYSX_UTILS_LIBRARY OSGPHYSX_INCLUDE_DIR)
  
  MARK_AS_ADVANCED(OSGPHYSX_LIBRARY OSGPHYSX_UTILS_LIBRARY OSGPHYSX_INCLUDE_DIR)
  
ENDIF(MSVC)

IF(OSGPHYSX_FOUND)
  SET(OSGPHYSX_INCLUDE_DIRS ${OSGPHYSX_INCLUDE_DIR})
ENDIF(OSGPHYSX_FOUND)
