##############################################################################
# search paths
##############################################################################
SET(OPENPASS_INCLUDE_SEARCH_DIRS
  $ENV{EXTERNLIBS}/OpenPASS/include
  $ENV{OPENPASS_HOME}/../../sim
  $ENV{COVISEDIR}/../simopenpass_hlrs/sim
  $ENV{COVISEDIR}/../simopenpass/sim
  ${GLOBAL_EXT_DIR}/OpenPASS/include
  ${GLOBAL_EXT_DIR}/include/OpenPASS
  ${OPENPASS_INCLUDE_SEARCH_DIR}
  /opt/OpenPASS/current
)

SET(OPENPASS_LIBRARY_SEARCH_DIRS
  $ENV{COVISEDIR}/../simopenpass/build/OpenPASS
  $ENV{EXTERNLIBS}/OpenPASS
  /opt/OpenPASS/current/lib/linux_x86
)

##############################################################################
# check for OpenPASS
##############################################################################

IF ( NOT OPENPASS_INCLUDE_DIRS )

    FOREACH(_SEARCH_DIR ${OPENPASS_INCLUDE_SEARCH_DIRS})
        FIND_PATH(_CUR_SEARCH
                NAMES include/agentInterface.h
                PATHS ${_SEARCH_DIR}
                NO_DEFAULT_PATH)
        IF (_CUR_SEARCH)
            LIST(APPEND _OPENPASS_FOUND_INC_DIRS ${_CUR_SEARCH})
        ENDIF(_CUR_SEARCH)
        SET(_CUR_SEARCH _CUR_SEARCH-NOTFOUND CACHE INTERNAL "internal use")
    ENDFOREACH(_SEARCH_DIR ${OPENPASS_INCLUDE_SEARCH_DIRS})


    FOREACH(_INC_DIR ${_OPENPASS_FOUND_INC_DIRS})
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/include)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/../)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/common)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/framework)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/importer)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/modelElements)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/modelInterface)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/observationInterface)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/scheduler)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/spawnPointInterface)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/stochasticsInterface)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/worldInterface)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulation/manipulatorInterface)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/opSimulationopSimulation/eventDetectorInterface)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/slave/collisionDetectionInterface)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core/common)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR}/src/core)
        LIST(APPEND _OPENPASS_INCLUDE_DIRS ${_INC_DIR})
    ENDFOREACH(_INC_DIR ${_BOOST_FOUND_INC_DIRS})

    IF (_OPENPASS_FOUND_INC_DIRS)
        SET(OPENPASS_INCLUDE_DIRS ${_OPENPASS_INCLUDE_DIRS} CACHE PATH "path to OPENPASS headers.")
    ENDIF (_OPENPASS_FOUND_INC_DIRS)

ENDIF ( NOT OPENPASS_INCLUDE_DIRS )

# release libraries
find_library(OPENPASS_COMMON_LIBRARY 
             NAMES Common
             PATHS ${OPENPASS_LIBRARY_SEARCH_DIRS}
             SUFFIXES bin
            )

find_library(OPENPASS_SIMULATION_CORE_LIBRARY 
             NAMES SimulationCore
             PATHS ${OPENPASS_LIBRARY_SEARCH_DIRS}
             SUFFIXES bin
            )

find_library(OPENPASS_CORE_COMMON_LIBRARY 
             NAMES CoreCommon
             PATHS ${OPENPASS_LIBRARY_SEARCH_DIRS}
             SUFFIXES bin
            )

			
# find debug libraries
find_library(OPENPASS_COMMON_LIBRARY_DEBUG
             NAMES Commond
             PATHS ${OPENPASS_LIBRARY_SEARCH_DIRS}
             SUFFIXES bin
            )

find_library(OPENPASS_SIMULATION_CORE_LIBRARY_DEBUG
             NAMES SimulationCored
             PATHS ${OPENPASS_LIBRARY_SEARCH_DIRS}
             SUFFIXES bin
            )

find_library(OPENPASS_CORE_COMMON_LIBRARY_DEBUG
             NAMES CoreCommond
             PATHS ${OPENPASS_LIBRARY_SEARCH_DIRS}
             SUFFIXES bin
            )


IF(MSVC)
  
  IF(OPENPASS_COMMON_LIBRARY_DEBUG AND OPENPASS_COMMON_LIBRARY)
    SET(OPENPASS_LIBRARIES optimized ${OPENPASS_COMMON_LIBRARY} debug ${OPENPASS_COMMON_LIBRARY_DEBUG} optimized ${OPENPASS_SIMULATION_CORE_LIBRARY} debug ${OPENPASS_SIMULATION_CORE_LIBRARY_DEBUG} optimized ${OPENPASS_CORE_COMMON_LIBRARY} debug ${OPENPASS_CORE_COMMON_LIBRARY_DEBUG})
  ENDIF(OPENPASS_COMMON_LIBRARY_DEBUG AND OPENPASS_COMMON_LIBRARY)

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENPASS DEFAULT_MSG OPENPASS_COMMON_LIBRARY OPENPASS_COMMON_LIBRARY_DEBUG OPENPASS_SIMULATION_CORE_LIBRARY OPENPASS_SIMULATION_CORE_LIBRARY_DEBUG OPENPASS_CORE_COMMON_LIBRARY OPENPASS_CORE_COMMON_LIBRARY_DEBUG )

  MARK_AS_ADVANCED(OPENPASS_COMMON_LIBRARY OPENPASS_COMMON_LIBRARY_DEBUG OPENPASS_SIMULATION_CORE_LIBRARY OPENPASS_SIMULATION_CORE_LIBRARY_DEBUG OPENPASS_CORE_COMMON_LIBRARY OPENPASS_CORE_COMMON_LIBRARY_DEBUG)
  
ELSE(MSVC)
  # rest of the world
    SET(OPENPASS_LIBRARIES ${OPENPASS_COMMON_LIBRARY} ${OPENPASS_SIMULATION_CORE_LIBRARY} ${OPENPASS_CORE_SHARED_LIBRARY})

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENPASS DEFAULT_MSG OPENPASS_COMMON_LIBRARY OPENPASS_SIMULATION_CORE_LIBRARY OPENPASS_CORE_COMMON_LIBRARY)
  
  MARK_AS_ADVANCED(OPENPASS_COMMON_LIBRARY  OPENPASS_SIMULATION_CORE_LIBRARY OPENPASS_CORE_COMMON_LIBRARY)
  
ENDIF(MSVC)
