# - Find ZSPACE
# Find the ZSPACE includes and library
#
#  ZSPACE_INCLUDE_DIR - Where to find ZSPACE includes
#  ZSPACE_LIBRARIES   - List of libraries when using ZSPACE
#  ZSPACE_FOUND       - True if ZSPACE was found

IF(ZSPACE_INCLUDE_DIR)
  SET(ZSPACE_FIND_QUIETLY TRUE)
ENDIF(ZSPACE_INCLUDE_DIR)

FIND_PATH(ZSPACE_INCLUDE_DIR "zSpace.h"
  PATHS
  $ENV{ZSPACE_HOME}/include
  $ENV{EXTERNLIBS}/zSpace/include
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw # Fink
  /opt/local # DarwinPorts
  /opt/csw # Blastwave
  /opt
  DOC "ZSPACE - Headers"
)

SET(ZSPACE_NAMES zSpaceApi64)
SET(ZSPACE_DBG_NAMES zSpaceApi64)

FIND_LIBRARY(ZSPACE_LIBRARY NAMES ${ZSPACE_NAMES}
  PATHS
  $ENV{ZSPACE_HOME}
  $ENV{EXTERNLIBS}/zSpace
  ~/Library/Frameworks
  /Library/Frameworks
  /usr/local
  /usr
  /sw
  /opt/local
  /opt/csw
  /opt
  PATH_SUFFIXES lib lib64
  DOC "ZSPACE - Library"
)

INCLUDE(FindPackageHandleStandardArgs)

IF(MSVC)
  # VisualStudio needs a debug version
  FIND_LIBRARY(ZSPACE_LIBRARY_DEBUG NAMES ${ZSPACE_DBG_NAMES}
    PATHS
    $ENV{ZSPACE_HOME}
    $ENV{EXTERNLIBS}/zSpace
    PATH_SUFFIXES lib lib64
    DOC "ZSPACE - Library (Debug)"
  )
  
  IF(ZSPACE_LIBRARY_DEBUG AND ZSPACE_LIBRARY)
    SET(ZSPACE_LIBRARIES optimized ${ZSPACE_LIBRARY} debug ${ZSPACE_LIBRARY_DEBUG})
  ENDIF(ZSPACE_LIBRARY_DEBUG AND ZSPACE_LIBRARY)

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZSPACE DEFAULT_MSG ZSPACE_LIBRARY ZSPACE_LIBRARY_DEBUG ZSPACE_INCLUDE_DIR)

  MARK_AS_ADVANCED(ZSPACE_LIBRARY ZSPACE_LIBRARY_DEBUG ZSPACE_INCLUDE_DIR)
  
ELSE(MSVC)
  # rest of the world
  SET(ZSPACE_LIBRARIES ${ZSPACE_LIBRARY})

  FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZSPACE DEFAULT_MSG ZSPACE_LIBRARY ZSPACE_INCLUDE_DIR)
  
  MARK_AS_ADVANCED(ZSPACE_LIBRARY ZSPACE_INCLUDE_DIR)
  
ENDIF(MSVC)

IF(ZSPACE_FOUND)
  SET(ZSPACE_INCLUDE_DIRS ${ZSPACE_INCLUDE_DIR})
ENDIF(ZSPACE_FOUND)
