
macro (GETENV_PATH var name)
   set(${var} $ENV{${name}})
   if (WIN32)
      string(REGEX REPLACE "\\\\" "/" ${var} "${${var}}")
   endif(WIN32)
endmacro (GETENV_PATH var name)

macro(find_qt)
   if (${ARGC} EQUAL 0)
     set(required "REQUIRED")
   endif()
   if(NOT COVISE_USE_QT5)
    covise_find_package(Qt6 COMPONENTS Core Gui Xml Network UiTools ${required} OPTIONAL_COMPONENTS WebEngineWidgets WebView Quick Svg SvgWidgets OpenGL OpenGLWidgets PrintSupport)
    set(CMAKE_CXX_STANDARD 17) #this is forced by Qt6 anyway, but since I dont' know how set this here so that we can check for it

    if (Qt6WebEngineWidgets_FOUND)
        set(COVISE_USE_WEBENGINE TRUE)
    endif()
   else()
      set(SAVED_CMAKE_PREFIX_PATH ${CMAKE_PREFIX_PATH})
      if (APPLE)
         set(CMAKE_PREFIX_PATH /opt/homebrew/opt/qt@5 ${CMAKE_PREFIX_PATH})
         set(CMAKE_PREFIX_PATH /usr/local/opt/qt@5 ${CMAKE_PREFIX_PATH})
      endif()
      if (NOT "$ENV{VCPKG_ROOT}" EQUAL "")
          set(CMAKE_PREFIX_PATH $ENV{VCPKG_ROOT}/installed/x64-windows ${CMAKE_PREFIX_PATH})
      endif()
	  GETENV_PATH(EXTERNLIBSQT EXTERNLIBS)
      STRING(REPLACE "/" \\ USING_FILES "${USING_FILES}")
      set(CMAKE_PREFIX_PATH ${EXTERNLIBSQT}/qt5 ${CMAKE_PREFIX_PATH})
      find_package(Qt5Core ${required})
      find_package(Qt5Network ${required})
      find_package(Qt5Xml ${required})
      find_package(Qt5Widgets ${required})
      find_package(Qt5OpenGL ${required})
      find_package(Qt5Gui ${required})
      find_package(Qt5Svg ${required})
      find_package(Qt5PrintSupport ${required})
      find_package(Qt5UiTools ${required})
      find_package(Qt5WebEngine QUIET)
      find_package(Qt5WebEngineWidgets QUIET)
      if (Qt5WebEngine_FOUND AND Qt5WebEngineWidgets_FOUND)
        set(COVISE_USE_WEBENGINE TRUE)
      else()
        find_package(Qt5WebKit QUIET)
        find_package(Qt5WebKitWidgets QUIET)
        if (Qt5WebKit_FOUND AND Qt5WebKitWidgets_FOUND)
          set(COVISE_USE_WEBKIT TRUE)
        endif()
      endif()
      find_package(Qt5Quick QUIET)
      if (Qt5Quick_FOUND)
          add_definitions(-DHAVE_QT_QUICK)
      endif()
      find_package(Qt5Location QUIET)
      if (Qt5Location_FOUND)
          add_definitions(-DHAVE_QT_LOCATION)
      endif()
      find_package(Qt5Positioning QUIET)
      if (Qt5Positioning_FOUND)
          add_definitions(-DHAVE_QT_POSITIONING)
      endif()
      find_package(Qt5Multimedia QUIET)
      if (Qt5Multimedia_FOUND)
          add_definitions(-DHAVE_QT_MULTIMEDIA)
      endif()
      find_package(Qt5Script QUIET)
      find_package(Qt5ScriptTools QUIET)
      if (Qt5Script_FOUND AND Qt5ScriptTools_FOUND)
          add_definitions(-DHAVE_QT_SCRIPT)
      endif()
      find_package(Qt5X11Extras QUIET)
      if (Qt5X11Extras_FOUND)
          set(-DHAVE_QT_X11EXTRAS)
      endif()
      set(CMAKE_PREFIX_PATH ${SAVED_CMAKE_PREFIX_PATH})
   endif()
endmacro(find_qt)

macro(qt_wrap_cpp)
    if(NOT COVISE_USE_QT5)
      qt6_wrap_cpp(${ARGV})
   else()
      qt5_wrap_cpp(${ARGV})
   endif()
endmacro(qt_wrap_cpp)

macro(qt_wrap_ui)
    IF(NOT COVISE_USE_QT5)
      qt6_wrap_ui(${ARGV})
   ELSE()
      qt5_wrap_ui(${ARGV})
   ENDIF()
endmacro(qt_wrap_ui)

macro(qt_add_resources)
    if(NOT COVISE_USE_QT5)
      qt6_add_resources(${ARGV})
   else()
      qt5_add_resources(${ARGV})
   endif()
endmacro(qt_add_resources)

macro(qt_use_modules target)
    if(NOT COVISE_USE_QT5)
        qt_disable_unicode_defines(${target})

       #target_include_directories(${target} SYSTEM ${Qt6${mod}_INCLUDE_DIRS})
       #target_link_libraries(${target} ${Qt6${mod}_LIBRARIES})
      foreach(mod ${ARGN})
          if (mod STREQUAL "Script" OR mod STREQUAL "ScriptTools")
          elseif (mod STREQUAL "WebEngine")
              set(mod WebEngineWidgets)
          else()
            #add_definitions(${Qt6${mod}_DEFINITIONS})
            #target_include_directories(${target} SYSTEM ${Qt6${mod}_INCLUDE_DIRS})
            #target_link_libraries(${target} ${Qt6${mod}_LIBRARIES})
            target_link_libraries(${target} Qt6::${mod})
         endif()
      endforeach()
   else()
      foreach(mod ${ARGN})
         if(mod STREQUAL "Qt3Support")
            message("Qt 5 does not include Qt3Support")
            return()
         endif()
         if (mod STREQUAL "Script")
             find_package(Qt5Script ${required})
         endif()
         if (mod STREQUAL "ScriptTools")
             find_package(Qt5ScriptTools ${required})
         endif()
         if (mod STREQUAL "Quick")
             find_package(Qt5Quick ${required})
         endif()
         if (mod STREQUAL "Positioning")
             find_package(Qt5Positioning ${required})
         endif()
         if (mod STREQUAL "Location")
             find_package(Qt5Location ${required})
         endif()
         if (mod STREQUAL "SvgWidgets")
             set(mod "Svg")
         endif()
         if (mod STREQUAL "OpenGLWidgets")
             set(mod "OpenGL")
         endif()
         add_definitions(${Qt5${mod}_DEFINITIONS})
         include_directories(SYSTEM ${Qt5${mod}_INCLUDE_DIRS})
         target_link_libraries(${target} ${Qt5${mod}_LIBRARIES})
      endforeach()
      #qt5_use_modules(${target} ${ARGN})
   endif()
endmacro(qt_use_modules)
