CONTAINER onavigationinfo
{
	NAME onavigationinfo;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		
		SEPARATOR
		{
			LINE;
		}
		STATICTEXT IDS_UEBERSCHRIFT { }
		LONG IDC_BASICUNITS { CYCLE { IDS_PIXEL; IDS_KILOMETER;IDS_METER;IDS_CENTIMETER;IDS_MILLIMETER;IDS_MICROMETER;IDS_NANOMETER;IDS_MILE;IDS_YARD;IDS_FOOT;IDS_INCH; }  }
		
		SEPARATOR
		{
			LINE;
		}
		STATICTEXT IDS_FELDER { }
		LONG IDC_TYPE { CYCLE { IDS_TYPE_ANY; IDS_TYPE_WALK;IDS_TYPE_EXAMINE;IDS_TYPE_FLY;IDS_TYPE_NONE; }  }
		GROUP
		{	
			COLUMNS 2;
			STATICTEXT IDS_HEADLIGHTS { }
			BOOL IDC_HEADLIGHT { }
		}
		
		STATICTEXT IDS_AVATAR_SIZE { }
		
		GROUP MY_GROUP
		{	
			REAL AVATAR_DISTANCE		{ UNIT METER; MIN 0.0; STEP 0.01;}
			REAL AVATAR_HEIGHT_TERRAIN	{ UNIT METER; MIN 0.0; STEP 0.01;}
			REAL AVATAR_HEIGHT_OBJECT	{ UNIT METER; MIN 0.0; STEP 0.01;}
		}
		REAL IDC_VISIBILITY_LIMIT { UNIT METER; MIN 0.0; STEP 0.01;}
	}
}
