
#version 430
uniform float osg_FrameTime;
layout (r32f, binding =0) uniform image2D targetTex;
layout (local_size_x = 16, local_size_y = 16) in;
void main() {
   ivec2 storePos = ivec2(gl_GlobalInvocationID.xy);
   float coeffcient = 0.5*sin(float(gl_WorkGroupID.x + gl_WorkGroupID.y)*0.1 + osg_FrameTime);
   coeffcient *= length(vec2(ivec2(gl_LocalInvocationID.xy) - ivec2(8)) / vec2(8.0));
   imageStore(targetTex, storePos, vec4(1.0-coeffcient, 0.0, 0.0, 0.0));
}